-- First, delete all existing dyeing costs to start fresh
DELETE FROM dyeing_costs;

-- Create a temporary function to insert dyeing costs by product code and color name
CREATE OR REPLACE FUNCTION insert_dyeing_cost_by_names(
  p_product_code TEXT,
  p_color_name TEXT,
  p_cost NUMERIC
) RETURNS VOID AS $$
DECLARE
  v_product_id UUID;
  v_color_id UUID;
BEGIN
  -- Get product ID
  SELECT id INTO v_product_id FROM products WHERE code = p_product_code AND is_active = true LIMIT 1;
  
  -- Get color ID (case insensitive, partial match)
  SELECT id INTO v_color_id FROM colors 
  WHERE UPPER(name) = UPPER(p_color_name) 
     OR UPPER(name) LIKE UPPER(p_color_name) || '%'
     OR UPPER(p_color_name) LIKE UPPER(name) || '%'
  LIMIT 1;
  
  -- Insert if both exist
  IF v_product_id IS NOT NULL AND v_color_id IS NOT NULL THEN
    INSERT INTO dyeing_costs (product_id, color_id, cost)
    VALUES (v_product_id, v_color_id, p_cost)
    ON CONFLICT DO NOTHING;
  END IF;
END;
$$ LANGUAGE plpgsql;

-- ==========================================
-- 001-AJ - ROMANTIC LISA (AJ)
-- ==========================================
SELECT insert_dyeing_cost_by_names('001-AJ', 'BRANCO', 7.62);
SELECT insert_dyeing_cost_by_names('001-AJ', 'PRETO', 9.90);
SELECT insert_dyeing_cost_by_names('001-AJ', 'ROMANCE', 7.70);
SELECT insert_dyeing_cost_by_names('001-AJ', 'FROZEN', 8.10);
SELECT insert_dyeing_cost_by_names('001-AJ', 'CHOCOLATE', 7.70);
SELECT insert_dyeing_cost_by_names('001-AJ', 'SATIN', 8.36);
SELECT insert_dyeing_cost_by_names('001-AJ', 'ROYAL', 9.13);
SELECT insert_dyeing_cost_by_names('001-AJ', 'JAIPUR', 9.84);
SELECT insert_dyeing_cost_by_names('001-AJ', 'FUCSIA', 9.84);
SELECT insert_dyeing_cost_by_names('001-AJ', 'RACY', 9.00);
SELECT insert_dyeing_cost_by_names('001-AJ', 'PINK', 9.00);
SELECT insert_dyeing_cost_by_names('001-AJ', 'ROSA BB', 7.99);
SELECT insert_dyeing_cost_by_names('001-AJ', 'AÇO', 8.20);
SELECT insert_dyeing_cost_by_names('001-AJ', 'VERMELHO', 9.98);
SELECT insert_dyeing_cost_by_names('001-AJ', 'MOCASSIM', 7.99);
SELECT insert_dyeing_cost_by_names('001-AJ', 'RUBRO', 8.78);
SELECT insert_dyeing_cost_by_names('001-AJ', 'PIMENTA', 9.64);
SELECT insert_dyeing_cost_by_names('001-AJ', 'TEOS', 7.70);
SELECT insert_dyeing_cost_by_names('001-AJ', 'CORAL', 8.04);
SELECT insert_dyeing_cost_by_names('001-AJ', 'TAME', 8.52);
SELECT insert_dyeing_cost_by_names('001-AJ', 'TW', 8.95);
SELECT insert_dyeing_cost_by_names('001-AJ', 'FANTÁSTICO', 8.41);
SELECT insert_dyeing_cost_by_names('001-AJ', 'MARINHO', 9.00);
SELECT insert_dyeing_cost_by_names('001-AJ', 'TERRA', 9.23);
SELECT insert_dyeing_cost_by_names('001-AJ', 'ATALAIA', 8.88);
SELECT insert_dyeing_cost_by_names('001-AJ', 'CASTANHO', 8.36);
SELECT insert_dyeing_cost_by_names('001-AJ', 'SANDIA', 8.31);
SELECT insert_dyeing_cost_by_names('001-AJ', 'VERDE NEON', 9.42);
SELECT insert_dyeing_cost_by_names('001-AJ', 'NINFA', 5.59);
SELECT insert_dyeing_cost_by_names('001-AJ', 'FRUTILLY', 5.59);
SELECT insert_dyeing_cost_by_names('001-AJ', 'AMARELO NEON', 0);
SELECT insert_dyeing_cost_by_names('001-AJ', 'ROSA FLUOR', 9.63);
SELECT insert_dyeing_cost_by_names('001-AJ', 'AZULEJO', 10.94);
SELECT insert_dyeing_cost_by_names('001-AJ', 'ODALÍSCA', 13.09);
SELECT insert_dyeing_cost_by_names('001-AJ', 'CHRONOS', 8.10);
SELECT insert_dyeing_cost_by_names('001-AJ', 'SANREMO', 8.04);
SELECT insert_dyeing_cost_by_names('001-AJ', 'LIPSTICK', 9.40);
SELECT insert_dyeing_cost_by_names('001-AJ', 'MARROCOS', 8.10);
SELECT insert_dyeing_cost_by_names('001-AJ', 'PANTERA', 8.57);
SELECT insert_dyeing_cost_by_names('001-AJ', 'AMARELO BISCOITO', 7.99);
SELECT insert_dyeing_cost_by_names('001-AJ', 'HERANÇA', 10.96);
SELECT insert_dyeing_cost_by_names('001-AJ', 'PAVÃO', 9.17);
SELECT insert_dyeing_cost_by_names('001-AJ', 'LOTERIA', 9.17);
SELECT insert_dyeing_cost_by_names('001-AJ', 'RUBRO RONALDO', 8.99);
SELECT insert_dyeing_cost_by_names('001-AJ', 'TURQUESA', 10.80);
SELECT insert_dyeing_cost_by_names('001-AJ', 'EROS', 8.68);
SELECT insert_dyeing_cost_by_names('001-AJ', 'FLORESTA', 8.90);
SELECT insert_dyeing_cost_by_names('001-AJ', 'RACY AMORECO', 13.50);
SELECT insert_dyeing_cost_by_names('001-AJ', 'PRETO AMORECO', 9.90);
SELECT insert_dyeing_cost_by_names('001-AJ', 'PETROLEO', 11.91);
SELECT insert_dyeing_cost_by_names('001-AJ', 'TERRA COTA', 9.23);
SELECT insert_dyeing_cost_by_names('001-AJ', 'AMÊNDOA', 8.47);
SELECT insert_dyeing_cost_by_names('001-AJ', 'MASTRUZ', 7.99);
SELECT insert_dyeing_cost_by_names('001-AJ', 'MOCHA MOUSSE', 8.57);
SELECT insert_dyeing_cost_by_names('001-AJ', 'AMÊNDOA BRONZE', 9.27);
SELECT insert_dyeing_cost_by_names('001-AJ', 'VERDE OLIVA', 8.62);
SELECT insert_dyeing_cost_by_names('001-AJ', 'COOFFE FLORATA', 10.77);
SELECT insert_dyeing_cost_by_names('001-AJ', 'COOFFE', 9.75);
SELECT insert_dyeing_cost_by_names('001-AJ', 'PRATA FLORATA', 8.44);
SELECT insert_dyeing_cost_by_names('001-AJ', 'VINHO FLORATA', 11.09);
SELECT insert_dyeing_cost_by_names('001-AJ', 'BIC IMPERIAL', 9.84);
SELECT insert_dyeing_cost_by_names('001-AJ', 'ERUS IMPERIAL', 9.24);
SELECT insert_dyeing_cost_by_names('001-AJ', 'RUBRO IMPERIAL', 9.84);
SELECT insert_dyeing_cost_by_names('001-AJ', 'TW IMPERIAL', 9.29);
SELECT insert_dyeing_cost_by_names('001-AJ', 'CHOCOLATE IMPERIAL', 8.29);
SELECT insert_dyeing_cost_by_names('001-AJ', 'AÇO IMPERIAL', 8.94);
SELECT insert_dyeing_cost_by_names('001-AJ', 'TURQUESA IMPERIAL', 9.94);
SELECT insert_dyeing_cost_by_names('001-AJ', 'VINHO', 8.78);
SELECT insert_dyeing_cost_by_names('001-AJ', 'BIC', 9.13);
SELECT insert_dyeing_cost_by_names('001-AJ', 'PRATA', 8.44);
SELECT insert_dyeing_cost_by_names('001-AJ', 'MAJOR', 8.20);
SELECT insert_dyeing_cost_by_names('001-AJ', 'CINZA MESCLA', 8.10);
SELECT insert_dyeing_cost_by_names('001-AJ', 'ESTAMPADO', 4.59);
SELECT insert_dyeing_cost_by_names('001-AJ', 'LAVAÇÃO', 4.59);

-- ==========================================
-- 001-PEDRINI - ROMANTIC LISA (Pedrini)
-- Same costs as 001-AJ
-- ==========================================
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'BRANCO', 7.62);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'PRETO', 9.90);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'ROMANCE', 7.70);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'FROZEN', 8.10);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'CHOCOLATE', 7.70);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'SATIN', 8.36);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'ROYAL', 9.13);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'JAIPUR', 9.84);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'FUCSIA', 9.84);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'RACY', 9.00);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'PINK', 9.00);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'ROSA BB', 7.99);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'AÇO', 8.20);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'VERMELHO', 9.98);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'MOCASSIM', 7.99);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'RUBRO', 8.78);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'PIMENTA', 9.64);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'TEOS', 7.70);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'CORAL', 8.04);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'TAME', 8.52);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'TW', 8.95);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'FANTÁSTICO', 8.41);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'MARINHO', 9.00);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'TERRA', 9.23);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'ATALAIA', 8.88);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'CASTANHO', 8.36);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'SANDIA', 8.31);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'VERDE NEON', 9.42);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'NINFA', 5.59);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'FRUTILLY', 5.59);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'AMARELO NEON', 0);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'ROSA FLUOR', 9.63);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'AZULEJO', 10.94);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'ODALÍSCA', 13.09);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'CHRONOS', 8.10);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'SANREMO', 8.04);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'LIPSTICK', 9.40);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'MARROCOS', 8.10);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'PANTERA', 8.57);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'AMARELO BISCOITO', 7.99);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'HERANÇA', 10.96);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'PAVÃO', 9.17);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'LOTERIA', 9.17);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'RUBRO RONALDO', 8.99);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'TURQUESA', 10.80);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'EROS', 8.68);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'FLORESTA', 8.90);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'RACY AMORECO', 13.50);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'PRETO AMORECO', 9.90);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'PETROLEO', 11.91);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'TERRA COTA', 9.23);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'AMÊNDOA', 8.47);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'MASTRUZ', 7.99);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'MOCHA MOUSSE', 8.57);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'AMÊNDOA BRONZE', 9.27);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'VERDE OLIVA', 8.62);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'COOFFE FLORATA', 10.77);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'COOFFE', 9.75);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'PRATA FLORATA', 8.44);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'VINHO FLORATA', 11.09);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'BIC IMPERIAL', 9.84);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'ERUS IMPERIAL', 9.24);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'RUBRO IMPERIAL', 9.84);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'TW IMPERIAL', 9.29);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'CHOCOLATE IMPERIAL', 8.29);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'AÇO IMPERIAL', 8.94);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'TURQUESA IMPERIAL', 9.94);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'VINHO', 8.78);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'BIC', 9.13);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'PRATA', 8.44);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'MAJOR', 8.20);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'CINZA MESCLA', 8.10);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'ESTAMPADO', 4.59);
SELECT insert_dyeing_cost_by_names('001-PEDRINI', 'LAVAÇÃO', 4.59);

-- ==========================================
-- 006 - ROMANTIC LISA 150 (same base costs)
-- ==========================================
SELECT insert_dyeing_cost_by_names('006', 'BRANCO', 7.62);
SELECT insert_dyeing_cost_by_names('006', 'PRETO', 9.90);
SELECT insert_dyeing_cost_by_names('006', 'ROMANCE', 7.70);
SELECT insert_dyeing_cost_by_names('006', 'FROZEN', 8.10);
SELECT insert_dyeing_cost_by_names('006', 'CHOCOLATE', 7.70);
SELECT insert_dyeing_cost_by_names('006', 'SATIN', 8.36);
SELECT insert_dyeing_cost_by_names('006', 'ROYAL', 9.13);
SELECT insert_dyeing_cost_by_names('006', 'JAIPUR', 9.84);
SELECT insert_dyeing_cost_by_names('006', 'RACY', 9.00);
SELECT insert_dyeing_cost_by_names('006', 'ROSA BB', 7.99);
SELECT insert_dyeing_cost_by_names('006', 'AÇO', 8.20);
SELECT insert_dyeing_cost_by_names('006', 'VERMELHO', 9.98);
SELECT insert_dyeing_cost_by_names('006', 'MOCASSIM', 7.99);
SELECT insert_dyeing_cost_by_names('006', 'RUBRO', 8.78);
SELECT insert_dyeing_cost_by_names('006', 'PIMENTA', 9.64);
SELECT insert_dyeing_cost_by_names('006', 'TEOS', 7.70);
SELECT insert_dyeing_cost_by_names('006', 'CORAL', 8.04);
SELECT insert_dyeing_cost_by_names('006', 'TAME', 8.52);
SELECT insert_dyeing_cost_by_names('006', 'TW', 8.95);
SELECT insert_dyeing_cost_by_names('006', 'FANTÁSTICO', 8.41);
SELECT insert_dyeing_cost_by_names('006', 'MARINHO', 9.00);
SELECT insert_dyeing_cost_by_names('006', 'TERRA', 9.23);
SELECT insert_dyeing_cost_by_names('006', 'ATALAIA', 8.88);
SELECT insert_dyeing_cost_by_names('006', 'CASTANHO', 8.36);
SELECT insert_dyeing_cost_by_names('006', 'SANDIA', 8.31);
SELECT insert_dyeing_cost_by_names('006', 'VERDE NEON', 9.42);
SELECT insert_dyeing_cost_by_names('006', 'NINFA', 5.59);
SELECT insert_dyeing_cost_by_names('006', 'ROSA FLUOR', 9.63);
SELECT insert_dyeing_cost_by_names('006', 'AZULEJO', 10.94);
SELECT insert_dyeing_cost_by_names('006', 'ODALÍSCA', 13.09);
SELECT insert_dyeing_cost_by_names('006', 'CHRONOS', 8.10);
SELECT insert_dyeing_cost_by_names('006', 'SANREMO', 8.04);
SELECT insert_dyeing_cost_by_names('006', 'LIPSTICK', 9.40);
SELECT insert_dyeing_cost_by_names('006', 'MARROCOS', 8.10);
SELECT insert_dyeing_cost_by_names('006', 'PANTERA', 8.57);
SELECT insert_dyeing_cost_by_names('006', 'AMARELO BISCOITO', 7.99);
SELECT insert_dyeing_cost_by_names('006', 'HERANÇA', 10.96);
SELECT insert_dyeing_cost_by_names('006', 'PAVÃO', 9.17);
SELECT insert_dyeing_cost_by_names('006', 'RUBRO RONALDO', 8.99);
SELECT insert_dyeing_cost_by_names('006', 'TURQUESA', 10.80);
SELECT insert_dyeing_cost_by_names('006', 'EROS', 8.68);
SELECT insert_dyeing_cost_by_names('006', 'FLORESTA', 8.90);
SELECT insert_dyeing_cost_by_names('006', 'PETROLEO', 11.91);
SELECT insert_dyeing_cost_by_names('006', 'TERRA COTA', 9.23);
SELECT insert_dyeing_cost_by_names('006', 'AMÊNDOA', 8.47);
SELECT insert_dyeing_cost_by_names('006', 'MASTRUZ', 7.99);
SELECT insert_dyeing_cost_by_names('006', 'MOCHA MOUSSE', 8.57);
SELECT insert_dyeing_cost_by_names('006', 'COOFFE', 9.75);
SELECT insert_dyeing_cost_by_names('006', 'VINHO', 8.78);
SELECT insert_dyeing_cost_by_names('006', 'BIC', 9.13);
SELECT insert_dyeing_cost_by_names('006', 'PRATA', 8.44);

-- ==========================================
-- 101 - SUPLEX LISO 320
-- ==========================================
SELECT insert_dyeing_cost_by_names('101', 'BRANCO', 7.62);
SELECT insert_dyeing_cost_by_names('101', 'PRETO', 9.90);
SELECT insert_dyeing_cost_by_names('101', 'ROMANCE', 7.70);
SELECT insert_dyeing_cost_by_names('101', 'FROZEN', 8.10);
SELECT insert_dyeing_cost_by_names('101', 'CHOCOLATE', 7.70);
SELECT insert_dyeing_cost_by_names('101', 'SATIN', 8.36);
SELECT insert_dyeing_cost_by_names('101', 'ROYAL', 9.13);
SELECT insert_dyeing_cost_by_names('101', 'JAIPUR', 9.84);
SELECT insert_dyeing_cost_by_names('101', 'RACY', 9.00);
SELECT insert_dyeing_cost_by_names('101', 'ROSA BB', 7.99);
SELECT insert_dyeing_cost_by_names('101', 'AÇO', 8.20);
SELECT insert_dyeing_cost_by_names('101', 'VERMELHO', 9.98);
SELECT insert_dyeing_cost_by_names('101', 'MOCASSIM', 7.99);
SELECT insert_dyeing_cost_by_names('101', 'RUBRO', 8.78);
SELECT insert_dyeing_cost_by_names('101', 'PIMENTA', 9.64);
SELECT insert_dyeing_cost_by_names('101', 'TEOS', 7.70);
SELECT insert_dyeing_cost_by_names('101', 'CORAL', 8.04);
SELECT insert_dyeing_cost_by_names('101', 'TAME', 8.52);
SELECT insert_dyeing_cost_by_names('101', 'TW', 8.95);
SELECT insert_dyeing_cost_by_names('101', 'FANTÁSTICO', 8.41);
SELECT insert_dyeing_cost_by_names('101', 'MARINHO', 9.00);
SELECT insert_dyeing_cost_by_names('101', 'TERRA', 9.23);
SELECT insert_dyeing_cost_by_names('101', 'ATALAIA', 8.88);
SELECT insert_dyeing_cost_by_names('101', 'CASTANHO', 8.36);
SELECT insert_dyeing_cost_by_names('101', 'SANDIA', 8.31);
SELECT insert_dyeing_cost_by_names('101', 'VERDE NEON', 9.42);
SELECT insert_dyeing_cost_by_names('101', 'NINFA', 5.59);
SELECT insert_dyeing_cost_by_names('101', 'ROSA FLUOR', 9.63);
SELECT insert_dyeing_cost_by_names('101', 'AZULEJO', 10.94);
SELECT insert_dyeing_cost_by_names('101', 'ODALÍSCA', 13.09);
SELECT insert_dyeing_cost_by_names('101', 'CHRONOS', 8.10);
SELECT insert_dyeing_cost_by_names('101', 'SANREMO', 8.04);
SELECT insert_dyeing_cost_by_names('101', 'LIPSTICK', 9.40);
SELECT insert_dyeing_cost_by_names('101', 'MARROCOS', 8.10);
SELECT insert_dyeing_cost_by_names('101', 'PANTERA', 8.57);
SELECT insert_dyeing_cost_by_names('101', 'AMARELO BISCOITO', 7.99);
SELECT insert_dyeing_cost_by_names('101', 'HERANÇA', 10.96);
SELECT insert_dyeing_cost_by_names('101', 'PAVÃO', 9.17);
SELECT insert_dyeing_cost_by_names('101', 'RUBRO RONALDO', 8.99);
SELECT insert_dyeing_cost_by_names('101', 'TURQUESA', 10.80);
SELECT insert_dyeing_cost_by_names('101', 'EROS', 8.68);
SELECT insert_dyeing_cost_by_names('101', 'FLORESTA', 8.90);
SELECT insert_dyeing_cost_by_names('101', 'PETROLEO', 11.91);
SELECT insert_dyeing_cost_by_names('101', 'TERRA COTA', 9.23);
SELECT insert_dyeing_cost_by_names('101', 'AMÊNDOA', 8.47);
SELECT insert_dyeing_cost_by_names('101', 'MASTRUZ', 7.99);
SELECT insert_dyeing_cost_by_names('101', 'MOCHA MOUSSE', 8.57);
SELECT insert_dyeing_cost_by_names('101', 'COOFFE', 9.75);
SELECT insert_dyeing_cost_by_names('101', 'VINHO', 8.78);
SELECT insert_dyeing_cost_by_names('101', 'BIC', 9.13);
SELECT insert_dyeing_cost_by_names('101', 'PRATA', 8.44);

-- ==========================================
-- 401-PEDRINI - MICROFIBRA POLIAMIDA (Pedrini) - DIFFERENT COSTS!
-- ==========================================
SELECT insert_dyeing_cost_by_names('401-PEDRINI', 'BRANCO', 9.29);
SELECT insert_dyeing_cost_by_names('401-PEDRINI', 'PRETO', 12.69);
SELECT insert_dyeing_cost_by_names('401-PEDRINI', 'ROMANCE', 9.99);
SELECT insert_dyeing_cost_by_names('401-PEDRINI', 'FROZEN', 10.29);
SELECT insert_dyeing_cost_by_names('401-PEDRINI', 'CHOCOLATE', 10.29);
SELECT insert_dyeing_cost_by_names('401-PEDRINI', 'SATIN', 10.69);
SELECT insert_dyeing_cost_by_names('401-PEDRINI', 'ROYAL', 11.44);
SELECT insert_dyeing_cost_by_names('401-PEDRINI', 'JAIPUR', 12.10);
SELECT insert_dyeing_cost_by_names('401-PEDRINI', 'RACY', 11.29);
SELECT insert_dyeing_cost_by_names('401-PEDRINI', 'ROSA BB', 10.29);
SELECT insert_dyeing_cost_by_names('401-PEDRINI', 'AÇO', 10.49);
SELECT insert_dyeing_cost_by_names('401-PEDRINI', 'VERMELHO', 12.26);
SELECT insert_dyeing_cost_by_names('401-PEDRINI', 'MOCASSIM', 10.29);
SELECT insert_dyeing_cost_by_names('401-PEDRINI', 'RUBRO', 11.06);
SELECT insert_dyeing_cost_by_names('401-PEDRINI', 'PIMENTA', 11.91);
SELECT insert_dyeing_cost_by_names('401-PEDRINI', 'TEOS', 9.99);
SELECT insert_dyeing_cost_by_names('401-PEDRINI', 'CORAL', 10.33);
SELECT insert_dyeing_cost_by_names('401-PEDRINI', 'TAME', 10.81);
SELECT insert_dyeing_cost_by_names('401-PEDRINI', 'TW', 11.23);
SELECT insert_dyeing_cost_by_names('401-PEDRINI', 'FANTÁSTICO', 10.69);
SELECT insert_dyeing_cost_by_names('401-PEDRINI', 'MARINHO', 11.29);
SELECT insert_dyeing_cost_by_names('401-PEDRINI', 'TERRA', 11.51);
SELECT insert_dyeing_cost_by_names('401-PEDRINI', 'ATALAIA', 11.16);
SELECT insert_dyeing_cost_by_names('401-PEDRINI', 'CASTANHO', 10.65);
SELECT insert_dyeing_cost_by_names('401-PEDRINI', 'SANDIA', 10.59);
SELECT insert_dyeing_cost_by_names('401-PEDRINI', 'VERDE NEON', 11.70);
SELECT insert_dyeing_cost_by_names('401-PEDRINI', 'NINFA', 7.87);
SELECT insert_dyeing_cost_by_names('401-PEDRINI', 'ROSA FLUOR', 11.91);
SELECT insert_dyeing_cost_by_names('401-PEDRINI', 'AZULEJO', 13.22);
SELECT insert_dyeing_cost_by_names('401-PEDRINI', 'ODALÍSCA', 15.37);
SELECT insert_dyeing_cost_by_names('401-PEDRINI', 'CHRONOS', 10.38);
SELECT insert_dyeing_cost_by_names('401-PEDRINI', 'SANREMO', 10.33);
SELECT insert_dyeing_cost_by_names('401-PEDRINI', 'LIPSTICK', 11.68);
SELECT insert_dyeing_cost_by_names('401-PEDRINI', 'MARROCOS', 10.38);
SELECT insert_dyeing_cost_by_names('401-PEDRINI', 'PANTERA', 10.85);
SELECT insert_dyeing_cost_by_names('401-PEDRINI', 'AMARELO BISCOITO', 10.28);
SELECT insert_dyeing_cost_by_names('401-PEDRINI', 'HERANÇA', 13.25);
SELECT insert_dyeing_cost_by_names('401-PEDRINI', 'PAVÃO', 11.45);
SELECT insert_dyeing_cost_by_names('401-PEDRINI', 'RUBRO RONALDO', 11.27);
SELECT insert_dyeing_cost_by_names('401-PEDRINI', 'TURQUESA', 13.08);
SELECT insert_dyeing_cost_by_names('401-PEDRINI', 'EROS', 10.96);
SELECT insert_dyeing_cost_by_names('401-PEDRINI', 'FLORESTA', 11.18);
SELECT insert_dyeing_cost_by_names('401-PEDRINI', 'PETROLEO', 14.19);
SELECT insert_dyeing_cost_by_names('401-PEDRINI', 'TERRA COTA', 11.51);
SELECT insert_dyeing_cost_by_names('401-PEDRINI', 'AMÊNDOA', 10.75);
SELECT insert_dyeing_cost_by_names('401-PEDRINI', 'MASTRUZ', 10.28);
SELECT insert_dyeing_cost_by_names('401-PEDRINI', 'MOCHA MOUSSE', 10.85);
SELECT insert_dyeing_cost_by_names('401-PEDRINI', 'COOFFE', 12.04);
SELECT insert_dyeing_cost_by_names('401-PEDRINI', 'VINHO', 11.06);
SELECT insert_dyeing_cost_by_names('401-PEDRINI', 'BIC', 11.42);
SELECT insert_dyeing_cost_by_names('401-PEDRINI', 'PRATA', 10.73);

-- ==========================================
-- 401-AJ - MICROFIBRA POLIAMIDA (Martextil-AJ) - DIFFERENT COSTS!
-- ==========================================
SELECT insert_dyeing_cost_by_names('401-AJ', 'BRANCO', 9.29);
SELECT insert_dyeing_cost_by_names('401-AJ', 'PRETO', 12.69);
SELECT insert_dyeing_cost_by_names('401-AJ', 'ROMANCE', 9.99);
SELECT insert_dyeing_cost_by_names('401-AJ', 'FROZEN', 10.29);
SELECT insert_dyeing_cost_by_names('401-AJ', 'CHOCOLATE', 10.29);
SELECT insert_dyeing_cost_by_names('401-AJ', 'SATIN', 10.69);
SELECT insert_dyeing_cost_by_names('401-AJ', 'ROYAL', 11.44);
SELECT insert_dyeing_cost_by_names('401-AJ', 'JAIPUR', 12.10);
SELECT insert_dyeing_cost_by_names('401-AJ', 'RACY', 11.29);
SELECT insert_dyeing_cost_by_names('401-AJ', 'ROSA BB', 10.29);
SELECT insert_dyeing_cost_by_names('401-AJ', 'AÇO', 10.49);
SELECT insert_dyeing_cost_by_names('401-AJ', 'VERMELHO', 12.26);
SELECT insert_dyeing_cost_by_names('401-AJ', 'MOCASSIM', 10.29);
SELECT insert_dyeing_cost_by_names('401-AJ', 'RUBRO', 11.06);
SELECT insert_dyeing_cost_by_names('401-AJ', 'PIMENTA', 11.91);
SELECT insert_dyeing_cost_by_names('401-AJ', 'TEOS', 9.99);
SELECT insert_dyeing_cost_by_names('401-AJ', 'CORAL', 10.33);
SELECT insert_dyeing_cost_by_names('401-AJ', 'TAME', 10.81);
SELECT insert_dyeing_cost_by_names('401-AJ', 'TW', 11.23);
SELECT insert_dyeing_cost_by_names('401-AJ', 'FANTÁSTICO', 10.69);
SELECT insert_dyeing_cost_by_names('401-AJ', 'MARINHO', 11.29);
SELECT insert_dyeing_cost_by_names('401-AJ', 'TERRA', 11.51);
SELECT insert_dyeing_cost_by_names('401-AJ', 'ATALAIA', 11.16);
SELECT insert_dyeing_cost_by_names('401-AJ', 'CASTANHO', 10.65);
SELECT insert_dyeing_cost_by_names('401-AJ', 'SANDIA', 10.59);
SELECT insert_dyeing_cost_by_names('401-AJ', 'VERDE NEON', 11.70);
SELECT insert_dyeing_cost_by_names('401-AJ', 'NINFA', 7.87);
SELECT insert_dyeing_cost_by_names('401-AJ', 'ROSA FLUOR', 11.91);
SELECT insert_dyeing_cost_by_names('401-AJ', 'AZULEJO', 13.22);
SELECT insert_dyeing_cost_by_names('401-AJ', 'ODALÍSCA', 15.37);
SELECT insert_dyeing_cost_by_names('401-AJ', 'CHRONOS', 10.38);
SELECT insert_dyeing_cost_by_names('401-AJ', 'SANREMO', 10.33);
SELECT insert_dyeing_cost_by_names('401-AJ', 'LIPSTICK', 11.68);
SELECT insert_dyeing_cost_by_names('401-AJ', 'MARROCOS', 10.38);
SELECT insert_dyeing_cost_by_names('401-AJ', 'PANTERA', 10.85);
SELECT insert_dyeing_cost_by_names('401-AJ', 'AMARELO BISCOITO', 10.28);
SELECT insert_dyeing_cost_by_names('401-AJ', 'HERANÇA', 13.25);
SELECT insert_dyeing_cost_by_names('401-AJ', 'PAVÃO', 11.45);
SELECT insert_dyeing_cost_by_names('401-AJ', 'RUBRO RONALDO', 11.27);
SELECT insert_dyeing_cost_by_names('401-AJ', 'TURQUESA', 13.08);
SELECT insert_dyeing_cost_by_names('401-AJ', 'EROS', 10.96);
SELECT insert_dyeing_cost_by_names('401-AJ', 'FLORESTA', 11.18);
SELECT insert_dyeing_cost_by_names('401-AJ', 'PETROLEO', 14.19);
SELECT insert_dyeing_cost_by_names('401-AJ', 'TERRA COTA', 11.51);
SELECT insert_dyeing_cost_by_names('401-AJ', 'AMÊNDOA', 10.75);
SELECT insert_dyeing_cost_by_names('401-AJ', 'MASTRUZ', 10.28);
SELECT insert_dyeing_cost_by_names('401-AJ', 'MOCHA MOUSSE', 10.85);
SELECT insert_dyeing_cost_by_names('401-AJ', 'COOFFE', 12.04);
SELECT insert_dyeing_cost_by_names('401-AJ', 'VINHO', 11.06);
SELECT insert_dyeing_cost_by_names('401-AJ', 'BIC', 11.42);
SELECT insert_dyeing_cost_by_names('401-AJ', 'PRATA', 10.73);

-- ==========================================
-- Apply same dyeing costs to remaining products
-- Products with standard polyester base costs (like 001-AJ)
-- ==========================================

-- 002 - ROMANTIC CONFORT
SELECT insert_dyeing_cost_by_names('002', 'BRANCO', 7.62);
SELECT insert_dyeing_cost_by_names('002', 'PRETO', 9.90);
SELECT insert_dyeing_cost_by_names('002', 'ROMANCE', 7.70);
SELECT insert_dyeing_cost_by_names('002', 'FROZEN', 8.10);
SELECT insert_dyeing_cost_by_names('002', 'CHOCOLATE', 7.70);
SELECT insert_dyeing_cost_by_names('002', 'SATIN', 8.36);
SELECT insert_dyeing_cost_by_names('002', 'ROYAL', 9.13);
SELECT insert_dyeing_cost_by_names('002', 'JAIPUR', 9.84);
SELECT insert_dyeing_cost_by_names('002', 'RACY', 9.00);
SELECT insert_dyeing_cost_by_names('002', 'ROSA BB', 7.99);
SELECT insert_dyeing_cost_by_names('002', 'AÇO', 8.20);
SELECT insert_dyeing_cost_by_names('002', 'VERMELHO', 9.98);
SELECT insert_dyeing_cost_by_names('002', 'MOCASSIM', 7.99);
SELECT insert_dyeing_cost_by_names('002', 'RUBRO', 8.78);
SELECT insert_dyeing_cost_by_names('002', 'PIMENTA', 9.64);
SELECT insert_dyeing_cost_by_names('002', 'TEOS', 7.70);
SELECT insert_dyeing_cost_by_names('002', 'CORAL', 8.04);
SELECT insert_dyeing_cost_by_names('002', 'TAME', 8.52);
SELECT insert_dyeing_cost_by_names('002', 'TW', 8.95);
SELECT insert_dyeing_cost_by_names('002', 'FANTÁSTICO', 8.41);
SELECT insert_dyeing_cost_by_names('002', 'MARINHO', 9.00);
SELECT insert_dyeing_cost_by_names('002', 'TERRA', 9.23);
SELECT insert_dyeing_cost_by_names('002', 'ATALAIA', 8.88);
SELECT insert_dyeing_cost_by_names('002', 'CASTANHO', 8.36);
SELECT insert_dyeing_cost_by_names('002', 'SANDIA', 8.31);
SELECT insert_dyeing_cost_by_names('002', 'VERDE NEON', 9.42);
SELECT insert_dyeing_cost_by_names('002', 'NINFA', 5.59);
SELECT insert_dyeing_cost_by_names('002', 'ROSA FLUOR', 9.63);
SELECT insert_dyeing_cost_by_names('002', 'AZULEJO', 10.94);
SELECT insert_dyeing_cost_by_names('002', 'ODALÍSCA', 13.09);
SELECT insert_dyeing_cost_by_names('002', 'CHRONOS', 8.10);
SELECT insert_dyeing_cost_by_names('002', 'SANREMO', 8.04);
SELECT insert_dyeing_cost_by_names('002', 'LIPSTICK', 9.40);
SELECT insert_dyeing_cost_by_names('002', 'MARROCOS', 8.10);
SELECT insert_dyeing_cost_by_names('002', 'PANTERA', 8.57);
SELECT insert_dyeing_cost_by_names('002', 'AMARELO BISCOITO', 7.99);
SELECT insert_dyeing_cost_by_names('002', 'HERANÇA', 10.96);
SELECT insert_dyeing_cost_by_names('002', 'PAVÃO', 9.17);
SELECT insert_dyeing_cost_by_names('002', 'TURQUESA', 10.80);
SELECT insert_dyeing_cost_by_names('002', 'EROS', 8.68);
SELECT insert_dyeing_cost_by_names('002', 'FLORESTA', 8.90);
SELECT insert_dyeing_cost_by_names('002', 'PETROLEO', 11.91);
SELECT insert_dyeing_cost_by_names('002', 'TERRA COTA', 9.23);
SELECT insert_dyeing_cost_by_names('002', 'AMÊNDOA', 8.47);
SELECT insert_dyeing_cost_by_names('002', 'MASTRUZ', 7.99);
SELECT insert_dyeing_cost_by_names('002', 'MOCHA MOUSSE', 8.57);
SELECT insert_dyeing_cost_by_names('002', 'COOFFE', 9.75);
SELECT insert_dyeing_cost_by_names('002', 'VINHO', 8.78);
SELECT insert_dyeing_cost_by_names('002', 'BIC', 9.13);
SELECT insert_dyeing_cost_by_names('002', 'PRATA', 8.44);

-- 003 - ROMANTIC SLIM
SELECT insert_dyeing_cost_by_names('003', 'BRANCO', 7.62);
SELECT insert_dyeing_cost_by_names('003', 'PRETO', 9.90);
SELECT insert_dyeing_cost_by_names('003', 'ROMANCE', 7.70);
SELECT insert_dyeing_cost_by_names('003', 'FROZEN', 8.10);
SELECT insert_dyeing_cost_by_names('003', 'CHOCOLATE', 7.70);
SELECT insert_dyeing_cost_by_names('003', 'SATIN', 8.36);
SELECT insert_dyeing_cost_by_names('003', 'ROYAL', 9.13);
SELECT insert_dyeing_cost_by_names('003', 'JAIPUR', 9.84);
SELECT insert_dyeing_cost_by_names('003', 'RACY', 9.00);
SELECT insert_dyeing_cost_by_names('003', 'ROSA BB', 7.99);
SELECT insert_dyeing_cost_by_names('003', 'AÇO', 8.20);
SELECT insert_dyeing_cost_by_names('003', 'VERMELHO', 9.98);
SELECT insert_dyeing_cost_by_names('003', 'MOCASSIM', 7.99);
SELECT insert_dyeing_cost_by_names('003', 'RUBRO', 8.78);
SELECT insert_dyeing_cost_by_names('003', 'PIMENTA', 9.64);
SELECT insert_dyeing_cost_by_names('003', 'TEOS', 7.70);
SELECT insert_dyeing_cost_by_names('003', 'CORAL', 8.04);
SELECT insert_dyeing_cost_by_names('003', 'TAME', 8.52);
SELECT insert_dyeing_cost_by_names('003', 'TW', 8.95);
SELECT insert_dyeing_cost_by_names('003', 'FANTÁSTICO', 8.41);
SELECT insert_dyeing_cost_by_names('003', 'MARINHO', 9.00);
SELECT insert_dyeing_cost_by_names('003', 'TERRA', 9.23);
SELECT insert_dyeing_cost_by_names('003', 'ATALAIA', 8.88);
SELECT insert_dyeing_cost_by_names('003', 'CASTANHO', 8.36);
SELECT insert_dyeing_cost_by_names('003', 'SANDIA', 8.31);
SELECT insert_dyeing_cost_by_names('003', 'VERDE NEON', 9.42);
SELECT insert_dyeing_cost_by_names('003', 'NINFA', 5.59);
SELECT insert_dyeing_cost_by_names('003', 'ROSA FLUOR', 9.63);
SELECT insert_dyeing_cost_by_names('003', 'AZULEJO', 10.94);
SELECT insert_dyeing_cost_by_names('003', 'ODALÍSCA', 13.09);
SELECT insert_dyeing_cost_by_names('003', 'CHRONOS', 8.10);
SELECT insert_dyeing_cost_by_names('003', 'SANREMO', 8.04);
SELECT insert_dyeing_cost_by_names('003', 'LIPSTICK', 9.40);
SELECT insert_dyeing_cost_by_names('003', 'MARROCOS', 8.10);
SELECT insert_dyeing_cost_by_names('003', 'PANTERA', 8.57);
SELECT insert_dyeing_cost_by_names('003', 'AMARELO BISCOITO', 7.99);
SELECT insert_dyeing_cost_by_names('003', 'HERANÇA', 10.96);
SELECT insert_dyeing_cost_by_names('003', 'PAVÃO', 9.17);
SELECT insert_dyeing_cost_by_names('003', 'TURQUESA', 10.80);
SELECT insert_dyeing_cost_by_names('003', 'EROS', 8.68);
SELECT insert_dyeing_cost_by_names('003', 'FLORESTA', 8.90);
SELECT insert_dyeing_cost_by_names('003', 'PETROLEO', 11.91);
SELECT insert_dyeing_cost_by_names('003', 'TERRA COTA', 9.23);
SELECT insert_dyeing_cost_by_names('003', 'AMÊNDOA', 8.47);
SELECT insert_dyeing_cost_by_names('003', 'MASTRUZ', 7.99);
SELECT insert_dyeing_cost_by_names('003', 'MOCHA MOUSSE', 8.57);
SELECT insert_dyeing_cost_by_names('003', 'COOFFE', 9.75);
SELECT insert_dyeing_cost_by_names('003', 'VINHO', 8.78);
SELECT insert_dyeing_cost_by_names('003', 'BIC', 9.13);
SELECT insert_dyeing_cost_by_names('003', 'PRATA', 8.44);

-- 004 - ROMANTIC RAJADO (same costs as standard polyester)
SELECT insert_dyeing_cost_by_names('004', 'BRANCO', 6.54);
SELECT insert_dyeing_cost_by_names('004', 'PRETO', 8.59);
SELECT insert_dyeing_cost_by_names('004', 'ROMANCE', 6.54);
SELECT insert_dyeing_cost_by_names('004', 'FROZEN', 6.79);
SELECT insert_dyeing_cost_by_names('004', 'CHOCOLATE', 6.69);
SELECT insert_dyeing_cost_by_names('004', 'SATIN', 6.43);
SELECT insert_dyeing_cost_by_names('004', 'JAIPUR', 8.19);
SELECT insert_dyeing_cost_by_names('004', 'AÇO', 6.89);
SELECT insert_dyeing_cost_by_names('004', 'VERMELHO', 6.54);
SELECT insert_dyeing_cost_by_names('004', 'RUBRO', 8.09);
SELECT insert_dyeing_cost_by_names('004', 'PIMENTA', 9.44);
SELECT insert_dyeing_cost_by_names('004', 'TEOS', 6.54);
SELECT insert_dyeing_cost_by_names('004', 'BIC', 8.34);
SELECT insert_dyeing_cost_by_names('004', 'TW', 7.59);
SELECT insert_dyeing_cost_by_names('004', 'MARINHO', 8.69);
SELECT insert_dyeing_cost_by_names('004', 'TAME', 10.93);
SELECT insert_dyeing_cost_by_names('004', 'TERRA', 7.99);

-- 100 - SUPLEX ZERO TRANSPARÊNCIA EVIDENCE 310
SELECT insert_dyeing_cost_by_names('100', 'BRANCO', 8.52);
SELECT insert_dyeing_cost_by_names('100', 'PRETO', 10.80);
SELECT insert_dyeing_cost_by_names('100', 'ROMANCE', 8.60);
SELECT insert_dyeing_cost_by_names('100', 'FROZEN', 9.00);
SELECT insert_dyeing_cost_by_names('100', 'CHOCOLATE', 8.60);
SELECT insert_dyeing_cost_by_names('100', 'SATIN', 9.26);
SELECT insert_dyeing_cost_by_names('100', 'ROYAL', 10.03);
SELECT insert_dyeing_cost_by_names('100', 'JAIPUR', 10.74);
SELECT insert_dyeing_cost_by_names('100', 'RACY', 9.90);
SELECT insert_dyeing_cost_by_names('100', 'ROSA BB', 8.89);
SELECT insert_dyeing_cost_by_names('100', 'AÇO', 9.10);
SELECT insert_dyeing_cost_by_names('100', 'VERMELHO', 10.88);
SELECT insert_dyeing_cost_by_names('100', 'MOCASSIM', 8.89);
SELECT insert_dyeing_cost_by_names('100', 'RUBRO', 9.68);
SELECT insert_dyeing_cost_by_names('100', 'PIMENTA', 10.54);
SELECT insert_dyeing_cost_by_names('100', 'TEOS', 8.60);
SELECT insert_dyeing_cost_by_names('100', 'CORAL', 8.94);
SELECT insert_dyeing_cost_by_names('100', 'TAME', 9.42);
SELECT insert_dyeing_cost_by_names('100', 'TW', 9.85);
SELECT insert_dyeing_cost_by_names('100', 'FANTÁSTICO', 9.31);
SELECT insert_dyeing_cost_by_names('100', 'MARINHO', 9.90);
SELECT insert_dyeing_cost_by_names('100', 'TERRA', 10.13);
SELECT insert_dyeing_cost_by_names('100', 'ATALAIA', 9.78);
SELECT insert_dyeing_cost_by_names('100', 'CASTANHO', 9.26);
SELECT insert_dyeing_cost_by_names('100', 'SANDIA', 9.21);
SELECT insert_dyeing_cost_by_names('100', 'VERDE NEON', 10.32);
SELECT insert_dyeing_cost_by_names('100', 'NINFA', 10.08);
SELECT insert_dyeing_cost_by_names('100', 'ROSA FLUOR', 10.53);
SELECT insert_dyeing_cost_by_names('100', 'AZULEJO', 11.84);
SELECT insert_dyeing_cost_by_names('100', 'ODALÍSCA', 13.99);
SELECT insert_dyeing_cost_by_names('100', 'CHRONOS', 9.00);
SELECT insert_dyeing_cost_by_names('100', 'SANREMO', 8.94);
SELECT insert_dyeing_cost_by_names('100', 'LIPSTICK', 10.30);
SELECT insert_dyeing_cost_by_names('100', 'MARROCOS', 9.00);
SELECT insert_dyeing_cost_by_names('100', 'PANTERA', 9.47);
SELECT insert_dyeing_cost_by_names('100', 'AMARELO BISCOITO', 8.89);
SELECT insert_dyeing_cost_by_names('100', 'HERANÇA', 11.86);
SELECT insert_dyeing_cost_by_names('100', 'PAVÃO', 10.07);
SELECT insert_dyeing_cost_by_names('100', 'RUBRO RONALDO', 9.89);
SELECT insert_dyeing_cost_by_names('100', 'TURQUESA', 11.70);
SELECT insert_dyeing_cost_by_names('100', 'EROS', 9.58);
SELECT insert_dyeing_cost_by_names('100', 'FLORESTA', 9.80);
SELECT insert_dyeing_cost_by_names('100', 'PETROLEO', 12.81);
SELECT insert_dyeing_cost_by_names('100', 'TERRA COTA', 10.13);
SELECT insert_dyeing_cost_by_names('100', 'AMÊNDOA', 9.37);
SELECT insert_dyeing_cost_by_names('100', 'MASTRUZ', 8.89);
SELECT insert_dyeing_cost_by_names('100', 'MOCHA MOUSSE', 9.47);
SELECT insert_dyeing_cost_by_names('100', 'COOFFE', 10.65);
SELECT insert_dyeing_cost_by_names('100', 'VINHO', 9.68);
SELECT insert_dyeing_cost_by_names('100', 'BIC', 10.03);
SELECT insert_dyeing_cost_by_names('100', 'PRATA', 9.34);

-- 102 - SUPLEX LISO ZERO TRANSPARÊNCIA 280
SELECT insert_dyeing_cost_by_names('102', 'BRANCO', 7.62);
SELECT insert_dyeing_cost_by_names('102', 'PRETO', 9.90);
SELECT insert_dyeing_cost_by_names('102', 'ROMANCE', 7.70);
SELECT insert_dyeing_cost_by_names('102', 'FROZEN', 8.10);
SELECT insert_dyeing_cost_by_names('102', 'CHOCOLATE', 7.70);
SELECT insert_dyeing_cost_by_names('102', 'SATIN', 8.36);
SELECT insert_dyeing_cost_by_names('102', 'ROYAL', 9.13);
SELECT insert_dyeing_cost_by_names('102', 'JAIPUR', 9.84);
SELECT insert_dyeing_cost_by_names('102', 'RACY', 9.00);
SELECT insert_dyeing_cost_by_names('102', 'ROSA BB', 7.99);
SELECT insert_dyeing_cost_by_names('102', 'AÇO', 8.20);
SELECT insert_dyeing_cost_by_names('102', 'VERMELHO', 9.98);
SELECT insert_dyeing_cost_by_names('102', 'MOCASSIM', 7.99);
SELECT insert_dyeing_cost_by_names('102', 'RUBRO', 8.78);
SELECT insert_dyeing_cost_by_names('102', 'PIMENTA', 9.64);
SELECT insert_dyeing_cost_by_names('102', 'TEOS', 7.70);
SELECT insert_dyeing_cost_by_names('102', 'CORAL', 8.04);
SELECT insert_dyeing_cost_by_names('102', 'TAME', 8.52);
SELECT insert_dyeing_cost_by_names('102', 'TW', 8.95);
SELECT insert_dyeing_cost_by_names('102', 'FANTÁSTICO', 8.41);
SELECT insert_dyeing_cost_by_names('102', 'MARINHO', 9.00);
SELECT insert_dyeing_cost_by_names('102', 'TERRA', 9.23);
SELECT insert_dyeing_cost_by_names('102', 'ATALAIA', 8.88);
SELECT insert_dyeing_cost_by_names('102', 'CASTANHO', 8.36);
SELECT insert_dyeing_cost_by_names('102', 'SANDIA', 8.31);
SELECT insert_dyeing_cost_by_names('102', 'VERDE NEON', 9.42);
SELECT insert_dyeing_cost_by_names('102', 'NINFA', 5.59);
SELECT insert_dyeing_cost_by_names('102', 'ROSA FLUOR', 9.63);
SELECT insert_dyeing_cost_by_names('102', 'AZULEJO', 10.94);
SELECT insert_dyeing_cost_by_names('102', 'ODALÍSCA', 13.09);
SELECT insert_dyeing_cost_by_names('102', 'CHRONOS', 8.10);
SELECT insert_dyeing_cost_by_names('102', 'SANREMO', 8.04);
SELECT insert_dyeing_cost_by_names('102', 'LIPSTICK', 9.40);
SELECT insert_dyeing_cost_by_names('102', 'MARROCOS', 8.10);
SELECT insert_dyeing_cost_by_names('102', 'PANTERA', 8.57);
SELECT insert_dyeing_cost_by_names('102', 'AMARELO BISCOITO', 7.99);
SELECT insert_dyeing_cost_by_names('102', 'HERANÇA', 10.96);
SELECT insert_dyeing_cost_by_names('102', 'PAVÃO', 9.17);
SELECT insert_dyeing_cost_by_names('102', 'TURQUESA', 10.80);
SELECT insert_dyeing_cost_by_names('102', 'EROS', 8.68);
SELECT insert_dyeing_cost_by_names('102', 'FLORESTA', 8.90);
SELECT insert_dyeing_cost_by_names('102', 'PETROLEO', 11.91);
SELECT insert_dyeing_cost_by_names('102', 'TERRA COTA', 9.23);
SELECT insert_dyeing_cost_by_names('102', 'AMÊNDOA', 8.47);
SELECT insert_dyeing_cost_by_names('102', 'MASTRUZ', 7.99);
SELECT insert_dyeing_cost_by_names('102', 'MOCHA MOUSSE', 8.57);
SELECT insert_dyeing_cost_by_names('102', 'COOFFE', 9.75);
SELECT insert_dyeing_cost_by_names('102', 'VINHO', 8.78);
SELECT insert_dyeing_cost_by_names('102', 'BIC', 9.13);
SELECT insert_dyeing_cost_by_names('102', 'PRATA', 8.44);

-- 107 - SUPLEX LISO 260
SELECT insert_dyeing_cost_by_names('107', 'BRANCO', 7.62);
SELECT insert_dyeing_cost_by_names('107', 'PRETO', 9.90);
SELECT insert_dyeing_cost_by_names('107', 'ROMANCE', 7.70);
SELECT insert_dyeing_cost_by_names('107', 'FROZEN', 8.10);
SELECT insert_dyeing_cost_by_names('107', 'CHOCOLATE', 7.70);
SELECT insert_dyeing_cost_by_names('107', 'SATIN', 8.36);
SELECT insert_dyeing_cost_by_names('107', 'ROYAL', 9.13);
SELECT insert_dyeing_cost_by_names('107', 'JAIPUR', 9.84);
SELECT insert_dyeing_cost_by_names('107', 'RACY', 9.00);
SELECT insert_dyeing_cost_by_names('107', 'ROSA BB', 7.99);
SELECT insert_dyeing_cost_by_names('107', 'AÇO', 8.20);
SELECT insert_dyeing_cost_by_names('107', 'VERMELHO', 9.98);
SELECT insert_dyeing_cost_by_names('107', 'MOCASSIM', 7.99);
SELECT insert_dyeing_cost_by_names('107', 'RUBRO', 8.78);
SELECT insert_dyeing_cost_by_names('107', 'PIMENTA', 9.64);
SELECT insert_dyeing_cost_by_names('107', 'TEOS', 7.70);
SELECT insert_dyeing_cost_by_names('107', 'CORAL', 8.04);
SELECT insert_dyeing_cost_by_names('107', 'TAME', 8.52);
SELECT insert_dyeing_cost_by_names('107', 'TW', 8.95);
SELECT insert_dyeing_cost_by_names('107', 'FANTÁSTICO', 8.41);
SELECT insert_dyeing_cost_by_names('107', 'MARINHO', 9.00);
SELECT insert_dyeing_cost_by_names('107', 'TERRA', 9.23);
SELECT insert_dyeing_cost_by_names('107', 'ATALAIA', 8.88);
SELECT insert_dyeing_cost_by_names('107', 'CASTANHO', 8.36);
SELECT insert_dyeing_cost_by_names('107', 'SANDIA', 8.31);
SELECT insert_dyeing_cost_by_names('107', 'VERDE NEON', 9.42);
SELECT insert_dyeing_cost_by_names('107', 'NINFA', 5.59);
SELECT insert_dyeing_cost_by_names('107', 'ROSA FLUOR', 9.63);
SELECT insert_dyeing_cost_by_names('107', 'AZULEJO', 10.94);
SELECT insert_dyeing_cost_by_names('107', 'ODALÍSCA', 13.09);
SELECT insert_dyeing_cost_by_names('107', 'CHRONOS', 8.10);
SELECT insert_dyeing_cost_by_names('107', 'SANREMO', 8.04);
SELECT insert_dyeing_cost_by_names('107', 'LIPSTICK', 9.40);
SELECT insert_dyeing_cost_by_names('107', 'MARROCOS', 8.10);
SELECT insert_dyeing_cost_by_names('107', 'PANTERA', 8.57);
SELECT insert_dyeing_cost_by_names('107', 'AMARELO BISCOITO', 7.99);
SELECT insert_dyeing_cost_by_names('107', 'HERANÇA', 10.96);
SELECT insert_dyeing_cost_by_names('107', 'PAVÃO', 9.17);
SELECT insert_dyeing_cost_by_names('107', 'TURQUESA', 10.80);
SELECT insert_dyeing_cost_by_names('107', 'EROS', 8.68);
SELECT insert_dyeing_cost_by_names('107', 'FLORESTA', 8.90);
SELECT insert_dyeing_cost_by_names('107', 'PETROLEO', 11.91);
SELECT insert_dyeing_cost_by_names('107', 'TERRA COTA', 9.23);
SELECT insert_dyeing_cost_by_names('107', 'AMÊNDOA', 8.47);
SELECT insert_dyeing_cost_by_names('107', 'MASTRUZ', 7.99);
SELECT insert_dyeing_cost_by_names('107', 'MOCHA MOUSSE', 8.57);
SELECT insert_dyeing_cost_by_names('107', 'COOFFE', 9.75);
SELECT insert_dyeing_cost_by_names('107', 'VINHO', 8.78);
SELECT insert_dyeing_cost_by_names('107', 'BIC', 9.13);
SELECT insert_dyeing_cost_by_names('107', 'PRATA', 8.44);

-- 109 - SUPLEX LISO 280
SELECT insert_dyeing_cost_by_names('109', 'BRANCO', 7.62);
SELECT insert_dyeing_cost_by_names('109', 'PRETO', 9.90);
SELECT insert_dyeing_cost_by_names('109', 'ROMANCE', 7.70);
SELECT insert_dyeing_cost_by_names('109', 'FROZEN', 8.10);
SELECT insert_dyeing_cost_by_names('109', 'CHOCOLATE', 7.70);
SELECT insert_dyeing_cost_by_names('109', 'SATIN', 8.36);
SELECT insert_dyeing_cost_by_names('109', 'ROYAL', 9.13);
SELECT insert_dyeing_cost_by_names('109', 'JAIPUR', 9.84);
SELECT insert_dyeing_cost_by_names('109', 'RACY', 9.00);
SELECT insert_dyeing_cost_by_names('109', 'ROSA BB', 7.99);
SELECT insert_dyeing_cost_by_names('109', 'AÇO', 8.20);
SELECT insert_dyeing_cost_by_names('109', 'VERMELHO', 9.98);
SELECT insert_dyeing_cost_by_names('109', 'MOCASSIM', 7.99);
SELECT insert_dyeing_cost_by_names('109', 'RUBRO', 8.78);
SELECT insert_dyeing_cost_by_names('109', 'PIMENTA', 9.64);
SELECT insert_dyeing_cost_by_names('109', 'TEOS', 7.70);
SELECT insert_dyeing_cost_by_names('109', 'CORAL', 8.04);
SELECT insert_dyeing_cost_by_names('109', 'TAME', 8.52);
SELECT insert_dyeing_cost_by_names('109', 'TW', 8.95);
SELECT insert_dyeing_cost_by_names('109', 'FANTÁSTICO', 8.41);
SELECT insert_dyeing_cost_by_names('109', 'MARINHO', 9.00);
SELECT insert_dyeing_cost_by_names('109', 'TERRA', 9.23);
SELECT insert_dyeing_cost_by_names('109', 'ATALAIA', 8.88);
SELECT insert_dyeing_cost_by_names('109', 'CASTANHO', 8.36);
SELECT insert_dyeing_cost_by_names('109', 'SANDIA', 8.31);
SELECT insert_dyeing_cost_by_names('109', 'VERDE NEON', 9.42);
SELECT insert_dyeing_cost_by_names('109', 'NINFA', 5.59);
SELECT insert_dyeing_cost_by_names('109', 'ROSA FLUOR', 9.63);
SELECT insert_dyeing_cost_by_names('109', 'AZULEJO', 10.94);
SELECT insert_dyeing_cost_by_names('109', 'ODALÍSCA', 13.09);
SELECT insert_dyeing_cost_by_names('109', 'CHRONOS', 8.10);
SELECT insert_dyeing_cost_by_names('109', 'SANREMO', 8.04);
SELECT insert_dyeing_cost_by_names('109', 'LIPSTICK', 9.40);
SELECT insert_dyeing_cost_by_names('109', 'MARROCOS', 8.10);
SELECT insert_dyeing_cost_by_names('109', 'PANTERA', 8.57);
SELECT insert_dyeing_cost_by_names('109', 'AMARELO BISCOITO', 7.99);
SELECT insert_dyeing_cost_by_names('109', 'HERANÇA', 10.96);
SELECT insert_dyeing_cost_by_names('109', 'PAVÃO', 9.17);
SELECT insert_dyeing_cost_by_names('109', 'TURQUESA', 10.80);
SELECT insert_dyeing_cost_by_names('109', 'EROS', 8.68);
SELECT insert_dyeing_cost_by_names('109', 'FLORESTA', 8.90);
SELECT insert_dyeing_cost_by_names('109', 'PETROLEO', 11.91);
SELECT insert_dyeing_cost_by_names('109', 'TERRA COTA', 9.23);
SELECT insert_dyeing_cost_by_names('109', 'AMÊNDOA', 8.47);
SELECT insert_dyeing_cost_by_names('109', 'MASTRUZ', 7.99);
SELECT insert_dyeing_cost_by_names('109', 'MOCHA MOUSSE', 8.57);
SELECT insert_dyeing_cost_by_names('109', 'COOFFE', 9.75);
SELECT insert_dyeing_cost_by_names('109', 'VINHO', 8.78);
SELECT insert_dyeing_cost_by_names('109', 'BIC', 9.13);
SELECT insert_dyeing_cost_by_names('109', 'PRATA', 8.44);

-- 114 - MICROPOWER 280
SELECT insert_dyeing_cost_by_names('114', 'BRANCO', 7.62);
SELECT insert_dyeing_cost_by_names('114', 'PRETO', 9.90);
SELECT insert_dyeing_cost_by_names('114', 'ROMANCE', 7.70);
SELECT insert_dyeing_cost_by_names('114', 'FROZEN', 8.10);
SELECT insert_dyeing_cost_by_names('114', 'CHOCOLATE', 7.70);
SELECT insert_dyeing_cost_by_names('114', 'SATIN', 8.36);
SELECT insert_dyeing_cost_by_names('114', 'ROYAL', 9.13);
SELECT insert_dyeing_cost_by_names('114', 'JAIPUR', 9.84);
SELECT insert_dyeing_cost_by_names('114', 'RACY', 9.00);
SELECT insert_dyeing_cost_by_names('114', 'ROSA BB', 7.99);
SELECT insert_dyeing_cost_by_names('114', 'AÇO', 8.20);
SELECT insert_dyeing_cost_by_names('114', 'VERMELHO', 9.98);
SELECT insert_dyeing_cost_by_names('114', 'MOCASSIM', 7.99);
SELECT insert_dyeing_cost_by_names('114', 'RUBRO', 8.78);
SELECT insert_dyeing_cost_by_names('114', 'PIMENTA', 9.64);
SELECT insert_dyeing_cost_by_names('114', 'TEOS', 7.70);
SELECT insert_dyeing_cost_by_names('114', 'CORAL', 8.04);
SELECT insert_dyeing_cost_by_names('114', 'TAME', 8.52);
SELECT insert_dyeing_cost_by_names('114', 'TW', 8.95);
SELECT insert_dyeing_cost_by_names('114', 'FANTÁSTICO', 8.41);
SELECT insert_dyeing_cost_by_names('114', 'MARINHO', 9.00);
SELECT insert_dyeing_cost_by_names('114', 'TERRA', 9.23);
SELECT insert_dyeing_cost_by_names('114', 'ATALAIA', 8.88);
SELECT insert_dyeing_cost_by_names('114', 'CASTANHO', 8.36);
SELECT insert_dyeing_cost_by_names('114', 'SANDIA', 8.31);
SELECT insert_dyeing_cost_by_names('114', 'VERDE NEON', 9.42);
SELECT insert_dyeing_cost_by_names('114', 'NINFA', 5.59);
SELECT insert_dyeing_cost_by_names('114', 'ROSA FLUOR', 9.63);
SELECT insert_dyeing_cost_by_names('114', 'AZULEJO', 10.94);
SELECT insert_dyeing_cost_by_names('114', 'ODALÍSCA', 13.09);
SELECT insert_dyeing_cost_by_names('114', 'CHRONOS', 8.10);
SELECT insert_dyeing_cost_by_names('114', 'SANREMO', 8.04);
SELECT insert_dyeing_cost_by_names('114', 'LIPSTICK', 9.40);
SELECT insert_dyeing_cost_by_names('114', 'MARROCOS', 8.10);
SELECT insert_dyeing_cost_by_names('114', 'PANTERA', 8.57);
SELECT insert_dyeing_cost_by_names('114', 'AMARELO BISCOITO', 7.99);
SELECT insert_dyeing_cost_by_names('114', 'HERANÇA', 10.96);
SELECT insert_dyeing_cost_by_names('114', 'PAVÃO', 9.17);
SELECT insert_dyeing_cost_by_names('114', 'TURQUESA', 10.80);
SELECT insert_dyeing_cost_by_names('114', 'EROS', 8.68);
SELECT insert_dyeing_cost_by_names('114', 'FLORESTA', 8.90);
SELECT insert_dyeing_cost_by_names('114', 'PETROLEO', 11.91);
SELECT insert_dyeing_cost_by_names('114', 'TERRA COTA', 9.23);
SELECT insert_dyeing_cost_by_names('114', 'AMÊNDOA', 8.47);
SELECT insert_dyeing_cost_by_names('114', 'MASTRUZ', 7.99);
SELECT insert_dyeing_cost_by_names('114', 'MOCHA MOUSSE', 8.57);
SELECT insert_dyeing_cost_by_names('114', 'COOFFE', 9.75);
SELECT insert_dyeing_cost_by_names('114', 'VINHO', 8.78);
SELECT insert_dyeing_cost_by_names('114', 'BIC', 9.13);
SELECT insert_dyeing_cost_by_names('114', 'PRATA', 8.44);

-- 115 - SUPLEX POWER ZERO TRANSPARÊNCIA 300
SELECT insert_dyeing_cost_by_names('115', 'BRANCO', 7.62);
SELECT insert_dyeing_cost_by_names('115', 'PRETO', 9.90);
SELECT insert_dyeing_cost_by_names('115', 'ROMANCE', 7.70);
SELECT insert_dyeing_cost_by_names('115', 'FROZEN', 8.10);
SELECT insert_dyeing_cost_by_names('115', 'CHOCOLATE', 7.70);
SELECT insert_dyeing_cost_by_names('115', 'SATIN', 8.36);
SELECT insert_dyeing_cost_by_names('115', 'ROYAL', 9.13);
SELECT insert_dyeing_cost_by_names('115', 'JAIPUR', 9.84);
SELECT insert_dyeing_cost_by_names('115', 'RACY', 9.00);
SELECT insert_dyeing_cost_by_names('115', 'ROSA BB', 7.99);
SELECT insert_dyeing_cost_by_names('115', 'AÇO', 8.20);
SELECT insert_dyeing_cost_by_names('115', 'VERMELHO', 9.98);
SELECT insert_dyeing_cost_by_names('115', 'MOCASSIM', 7.99);
SELECT insert_dyeing_cost_by_names('115', 'RUBRO', 8.78);
SELECT insert_dyeing_cost_by_names('115', 'PIMENTA', 9.64);
SELECT insert_dyeing_cost_by_names('115', 'TEOS', 7.70);
SELECT insert_dyeing_cost_by_names('115', 'CORAL', 8.04);
SELECT insert_dyeing_cost_by_names('115', 'TAME', 8.52);
SELECT insert_dyeing_cost_by_names('115', 'TW', 8.95);
SELECT insert_dyeing_cost_by_names('115', 'FANTÁSTICO', 8.41);
SELECT insert_dyeing_cost_by_names('115', 'MARINHO', 9.00);
SELECT insert_dyeing_cost_by_names('115', 'TERRA', 9.23);
SELECT insert_dyeing_cost_by_names('115', 'ATALAIA', 8.88);
SELECT insert_dyeing_cost_by_names('115', 'CASTANHO', 8.36);
SELECT insert_dyeing_cost_by_names('115', 'SANDIA', 8.31);
SELECT insert_dyeing_cost_by_names('115', 'VERDE NEON', 9.42);
SELECT insert_dyeing_cost_by_names('115', 'NINFA', 5.59);
SELECT insert_dyeing_cost_by_names('115', 'ROSA FLUOR', 9.63);
SELECT insert_dyeing_cost_by_names('115', 'AZULEJO', 10.94);
SELECT insert_dyeing_cost_by_names('115', 'ODALÍSCA', 13.09);
SELECT insert_dyeing_cost_by_names('115', 'CHRONOS', 8.10);
SELECT insert_dyeing_cost_by_names('115', 'SANREMO', 8.04);
SELECT insert_dyeing_cost_by_names('115', 'LIPSTICK', 9.40);
SELECT insert_dyeing_cost_by_names('115', 'MARROCOS', 8.10);
SELECT insert_dyeing_cost_by_names('115', 'PANTERA', 8.57);
SELECT insert_dyeing_cost_by_names('115', 'AMARELO BISCOITO', 7.99);
SELECT insert_dyeing_cost_by_names('115', 'HERANÇA', 10.96);
SELECT insert_dyeing_cost_by_names('115', 'PAVÃO', 9.17);
SELECT insert_dyeing_cost_by_names('115', 'TURQUESA', 10.80);
SELECT insert_dyeing_cost_by_names('115', 'EROS', 8.68);
SELECT insert_dyeing_cost_by_names('115', 'FLORESTA', 8.90);
SELECT insert_dyeing_cost_by_names('115', 'PETROLEO', 11.91);
SELECT insert_dyeing_cost_by_names('115', 'TERRA COTA', 9.23);
SELECT insert_dyeing_cost_by_names('115', 'AMÊNDOA', 8.47);
SELECT insert_dyeing_cost_by_names('115', 'MASTRUZ', 7.99);
SELECT insert_dyeing_cost_by_names('115', 'MOCHA MOUSSE', 8.57);
SELECT insert_dyeing_cost_by_names('115', 'COOFFE', 9.75);
SELECT insert_dyeing_cost_by_names('115', 'VINHO', 8.78);
SELECT insert_dyeing_cost_by_names('115', 'BIC', 9.13);
SELECT insert_dyeing_cost_by_names('115', 'PRATA', 8.44);

-- Products with LAVAÇÃO/sublimation cost only
SELECT insert_dyeing_cost_by_names('005', 'LAVAÇÃO', 4.59);
SELECT insert_dyeing_cost_by_names('005-LIGHT', 'LAVAÇÃO', 4.59);
SELECT insert_dyeing_cost_by_names('155', 'LAVAÇÃO', 4.59);

-- SUPLEX BLACK products - only PRETO/LAVAÇÃO
SELECT insert_dyeing_cost_by_names('103', 'LAVAÇÃO', 4.59);
SELECT insert_dyeing_cost_by_names('116', 'LAVAÇÃO', 4.59);
SELECT insert_dyeing_cost_by_names('118', 'LAVAÇÃO', 4.59);

-- MESCLA products - special costs
SELECT insert_dyeing_cost_by_names('110', 'CINZA MESCLA', 4.59);
SELECT insert_dyeing_cost_by_names('111', 'CINZA MESCLA', 4.59);

-- 200/201 - CANELADO products
SELECT insert_dyeing_cost_by_names('200', 'BRANCO', 7.62);
SELECT insert_dyeing_cost_by_names('200', 'PRETO', 9.90);
SELECT insert_dyeing_cost_by_names('200', 'ROMANCE', 7.70);
SELECT insert_dyeing_cost_by_names('200', 'FROZEN', 8.10);
SELECT insert_dyeing_cost_by_names('200', 'CHOCOLATE', 7.70);
SELECT insert_dyeing_cost_by_names('200', 'SATIN', 8.36);
SELECT insert_dyeing_cost_by_names('200', 'ROYAL', 9.13);
SELECT insert_dyeing_cost_by_names('200', 'JAIPUR', 9.84);
SELECT insert_dyeing_cost_by_names('200', 'RACY', 9.00);
SELECT insert_dyeing_cost_by_names('200', 'ROSA BB', 7.99);
SELECT insert_dyeing_cost_by_names('200', 'AÇO', 8.20);
SELECT insert_dyeing_cost_by_names('200', 'VERMELHO', 9.98);
SELECT insert_dyeing_cost_by_names('200', 'MOCASSIM', 7.99);
SELECT insert_dyeing_cost_by_names('200', 'RUBRO', 8.78);
SELECT insert_dyeing_cost_by_names('200', 'PIMENTA', 9.64);
SELECT insert_dyeing_cost_by_names('200', 'TEOS', 7.70);
SELECT insert_dyeing_cost_by_names('200', 'CORAL', 8.04);
SELECT insert_dyeing_cost_by_names('200', 'TAME', 8.52);
SELECT insert_dyeing_cost_by_names('200', 'TW', 8.95);
SELECT insert_dyeing_cost_by_names('200', 'MARINHO', 9.00);
SELECT insert_dyeing_cost_by_names('200', 'TERRA', 9.23);
SELECT insert_dyeing_cost_by_names('200', 'CASTANHO', 8.36);
SELECT insert_dyeing_cost_by_names('200', 'VINHO', 8.78);
SELECT insert_dyeing_cost_by_names('200', 'BIC', 9.13);
SELECT insert_dyeing_cost_by_names('200', 'PRATA', 8.44);

SELECT insert_dyeing_cost_by_names('201', 'BRANCO', 7.62);
SELECT insert_dyeing_cost_by_names('201', 'PRETO', 9.90);
SELECT insert_dyeing_cost_by_names('201', 'ROMANCE', 7.70);
SELECT insert_dyeing_cost_by_names('201', 'FROZEN', 8.10);
SELECT insert_dyeing_cost_by_names('201', 'CHOCOLATE', 7.70);
SELECT insert_dyeing_cost_by_names('201', 'SATIN', 8.36);
SELECT insert_dyeing_cost_by_names('201', 'ROYAL', 9.13);
SELECT insert_dyeing_cost_by_names('201', 'JAIPUR', 9.84);
SELECT insert_dyeing_cost_by_names('201', 'RACY', 9.00);
SELECT insert_dyeing_cost_by_names('201', 'ROSA BB', 7.99);
SELECT insert_dyeing_cost_by_names('201', 'AÇO', 8.20);
SELECT insert_dyeing_cost_by_names('201', 'VERMELHO', 9.98);
SELECT insert_dyeing_cost_by_names('201', 'MOCASSIM', 7.99);
SELECT insert_dyeing_cost_by_names('201', 'RUBRO', 8.78);
SELECT insert_dyeing_cost_by_names('201', 'PIMENTA', 9.64);
SELECT insert_dyeing_cost_by_names('201', 'TEOS', 7.70);
SELECT insert_dyeing_cost_by_names('201', 'CORAL', 8.04);
SELECT insert_dyeing_cost_by_names('201', 'TAME', 8.52);
SELECT insert_dyeing_cost_by_names('201', 'TW', 8.95);
SELECT insert_dyeing_cost_by_names('201', 'MARINHO', 9.00);
SELECT insert_dyeing_cost_by_names('201', 'TERRA', 9.23);
SELECT insert_dyeing_cost_by_names('201', 'CASTANHO', 8.36);
SELECT insert_dyeing_cost_by_names('201', 'VINHO', 8.78);
SELECT insert_dyeing_cost_by_names('201', 'BIC', 9.13);
SELECT insert_dyeing_cost_by_names('201', 'PRATA', 8.44);

-- 301 - MEIA MALHA PP (different costs)
SELECT insert_dyeing_cost_by_names('301', 'BRANCO', 5.69);
SELECT insert_dyeing_cost_by_names('301', 'PRETO', 7.49);
SELECT insert_dyeing_cost_by_names('301', 'ROMANCE', 5.69);
SELECT insert_dyeing_cost_by_names('301', 'FROZEN', 5.69);
SELECT insert_dyeing_cost_by_names('301', 'CHOCOLATE', 7.49);
SELECT insert_dyeing_cost_by_names('301', 'SATIN', 7.49);
SELECT insert_dyeing_cost_by_names('301', 'JAIPUR', 7.49);
SELECT insert_dyeing_cost_by_names('301', 'AÇO', 7.49);
SELECT insert_dyeing_cost_by_names('301', 'VERMELHO', 7.49);
SELECT insert_dyeing_cost_by_names('301', 'MOCASSIM', 5.49);
SELECT insert_dyeing_cost_by_names('301', 'RUBRO', 7.49);
SELECT insert_dyeing_cost_by_names('301', 'PIMENTA', 8.19);
SELECT insert_dyeing_cost_by_names('301', 'TEOS', 5.99);
SELECT insert_dyeing_cost_by_names('301', 'BIC', 7.19);
SELECT insert_dyeing_cost_by_names('301', 'TAME', 7.29);
SELECT insert_dyeing_cost_by_names('301', 'TW', 8.09);
SELECT insert_dyeing_cost_by_names('301', 'FANTÁSTICO', 5.49);
SELECT insert_dyeing_cost_by_names('301', 'MARINHO', 7.49);
SELECT insert_dyeing_cost_by_names('301', 'TERRA', 7.29);
SELECT insert_dyeing_cost_by_names('301', 'CASTANHO', 5.39);

-- 307 - COTTON PENTEADO (cotton-based, different costs)
SELECT insert_dyeing_cost_by_names('307', 'BRANCO', 7.42);
SELECT insert_dyeing_cost_by_names('307', 'PRETO', 10.49);
SELECT insert_dyeing_cost_by_names('307', 'ROMANCE', 8.82);
SELECT insert_dyeing_cost_by_names('307', 'FROZEN', 8.93);
SELECT insert_dyeing_cost_by_names('307', 'CHOCOLATE', 8.73);
SELECT insert_dyeing_cost_by_names('307', 'SATIN', 9.55);
SELECT insert_dyeing_cost_by_names('307', 'ROYAL', 10.40);
SELECT insert_dyeing_cost_by_names('307', 'JAIPUR', 9.35);
SELECT insert_dyeing_cost_by_names('307', 'RACY', 9.07);
SELECT insert_dyeing_cost_by_names('307', 'ROSA BB', 8.59);
SELECT insert_dyeing_cost_by_names('307', 'AÇO', 9.82);
SELECT insert_dyeing_cost_by_names('307', 'VERMELHO', 9.98);
SELECT insert_dyeing_cost_by_names('307', 'MOCASSIM', 8.62);
SELECT insert_dyeing_cost_by_names('307', 'RUBRO', 9.26);
SELECT insert_dyeing_cost_by_names('307', 'PIMENTA', 10.28);
SELECT insert_dyeing_cost_by_names('307', 'TEOS', 8.73);
SELECT insert_dyeing_cost_by_names('307', 'CORAL', 8.64);
SELECT insert_dyeing_cost_by_names('307', 'TAME', 9.16);
SELECT insert_dyeing_cost_by_names('307', 'TW', 9.62);
SELECT insert_dyeing_cost_by_names('307', 'FANTÁSTICO', 8.68);
SELECT insert_dyeing_cost_by_names('307', 'MARINHO', 9.47);
SELECT insert_dyeing_cost_by_names('307', 'TERRA', 9.75);
SELECT insert_dyeing_cost_by_names('307', 'ATALAIA', 10.88);
SELECT insert_dyeing_cost_by_names('307', 'CASTANHO', 8.73);
SELECT insert_dyeing_cost_by_names('307', 'VINHO', 9.26);
SELECT insert_dyeing_cost_by_names('307', 'BIC', 10.40);
SELECT insert_dyeing_cost_by_names('307', 'PRATA', 9.42);

-- 308 - COTTON SUPER CARDADO (same as 307)
SELECT insert_dyeing_cost_by_names('308', 'BRANCO', 7.42);
SELECT insert_dyeing_cost_by_names('308', 'PRETO', 10.49);
SELECT insert_dyeing_cost_by_names('308', 'ROMANCE', 8.82);
SELECT insert_dyeing_cost_by_names('308', 'FROZEN', 8.93);
SELECT insert_dyeing_cost_by_names('308', 'CHOCOLATE', 8.73);
SELECT insert_dyeing_cost_by_names('308', 'SATIN', 9.55);
SELECT insert_dyeing_cost_by_names('308', 'ROYAL', 10.40);
SELECT insert_dyeing_cost_by_names('308', 'JAIPUR', 9.35);
SELECT insert_dyeing_cost_by_names('308', 'RACY', 9.07);
SELECT insert_dyeing_cost_by_names('308', 'ROSA BB', 8.59);
SELECT insert_dyeing_cost_by_names('308', 'AÇO', 9.82);
SELECT insert_dyeing_cost_by_names('308', 'VERMELHO', 9.98);
SELECT insert_dyeing_cost_by_names('308', 'MOCASSIM', 8.62);
SELECT insert_dyeing_cost_by_names('308', 'RUBRO', 9.26);
SELECT insert_dyeing_cost_by_names('308', 'PIMENTA', 10.28);
SELECT insert_dyeing_cost_by_names('308', 'TEOS', 8.73);
SELECT insert_dyeing_cost_by_names('308', 'CORAL', 8.64);
SELECT insert_dyeing_cost_by_names('308', 'TAME', 9.16);
SELECT insert_dyeing_cost_by_names('308', 'TW', 9.62);
SELECT insert_dyeing_cost_by_names('308', 'FANTÁSTICO', 8.68);
SELECT insert_dyeing_cost_by_names('308', 'MARINHO', 9.47);
SELECT insert_dyeing_cost_by_names('308', 'TERRA', 9.75);
SELECT insert_dyeing_cost_by_names('308', 'ATALAIA', 10.88);
SELECT insert_dyeing_cost_by_names('308', 'CASTANHO', 8.73);
SELECT insert_dyeing_cost_by_names('308', 'VINHO', 9.26);
SELECT insert_dyeing_cost_by_names('308', 'BIC', 10.40);
SELECT insert_dyeing_cost_by_names('308', 'PRATA', 9.42);

-- 501-504 - SUPLEX POLIAMIDA products (use 401 costs)
SELECT insert_dyeing_cost_by_names('501', 'BRANCO', 9.29);
SELECT insert_dyeing_cost_by_names('501', 'PRETO', 12.69);
SELECT insert_dyeing_cost_by_names('501', 'ROMANCE', 9.99);
SELECT insert_dyeing_cost_by_names('501', 'FROZEN', 10.29);
SELECT insert_dyeing_cost_by_names('501', 'CHOCOLATE', 10.29);
SELECT insert_dyeing_cost_by_names('501', 'SATIN', 10.69);
SELECT insert_dyeing_cost_by_names('501', 'ROYAL', 11.44);
SELECT insert_dyeing_cost_by_names('501', 'JAIPUR', 12.10);
SELECT insert_dyeing_cost_by_names('501', 'RACY', 11.29);
SELECT insert_dyeing_cost_by_names('501', 'ROSA BB', 10.29);
SELECT insert_dyeing_cost_by_names('501', 'AÇO', 10.49);
SELECT insert_dyeing_cost_by_names('501', 'VERMELHO', 12.26);
SELECT insert_dyeing_cost_by_names('501', 'MOCASSIM', 10.29);
SELECT insert_dyeing_cost_by_names('501', 'RUBRO', 11.06);
SELECT insert_dyeing_cost_by_names('501', 'PIMENTA', 11.91);
SELECT insert_dyeing_cost_by_names('501', 'TEOS', 9.99);
SELECT insert_dyeing_cost_by_names('501', 'CORAL', 10.33);
SELECT insert_dyeing_cost_by_names('501', 'TAME', 10.81);
SELECT insert_dyeing_cost_by_names('501', 'TW', 11.23);
SELECT insert_dyeing_cost_by_names('501', 'FANTÁSTICO', 10.69);
SELECT insert_dyeing_cost_by_names('501', 'MARINHO', 11.29);
SELECT insert_dyeing_cost_by_names('501', 'TERRA', 11.51);
SELECT insert_dyeing_cost_by_names('501', 'CASTANHO', 10.65);
SELECT insert_dyeing_cost_by_names('501', 'VINHO', 11.06);
SELECT insert_dyeing_cost_by_names('501', 'BIC', 11.42);
SELECT insert_dyeing_cost_by_names('501', 'PRATA', 10.73);

SELECT insert_dyeing_cost_by_names('502', 'BRANCO', 9.29);
SELECT insert_dyeing_cost_by_names('502', 'PRETO', 12.69);
SELECT insert_dyeing_cost_by_names('502', 'ROMANCE', 9.99);
SELECT insert_dyeing_cost_by_names('502', 'FROZEN', 10.29);
SELECT insert_dyeing_cost_by_names('502', 'CHOCOLATE', 10.29);
SELECT insert_dyeing_cost_by_names('502', 'SATIN', 10.69);
SELECT insert_dyeing_cost_by_names('502', 'ROYAL', 11.44);
SELECT insert_dyeing_cost_by_names('502', 'JAIPUR', 12.10);
SELECT insert_dyeing_cost_by_names('502', 'RACY', 11.29);
SELECT insert_dyeing_cost_by_names('502', 'ROSA BB', 10.29);
SELECT insert_dyeing_cost_by_names('502', 'AÇO', 10.49);
SELECT insert_dyeing_cost_by_names('502', 'VERMELHO', 12.26);
SELECT insert_dyeing_cost_by_names('502', 'MOCASSIM', 10.29);
SELECT insert_dyeing_cost_by_names('502', 'RUBRO', 11.06);
SELECT insert_dyeing_cost_by_names('502', 'PIMENTA', 11.91);
SELECT insert_dyeing_cost_by_names('502', 'TEOS', 9.99);
SELECT insert_dyeing_cost_by_names('502', 'CORAL', 10.33);
SELECT insert_dyeing_cost_by_names('502', 'TAME', 10.81);
SELECT insert_dyeing_cost_by_names('502', 'TW', 11.23);
SELECT insert_dyeing_cost_by_names('502', 'MARINHO', 11.29);
SELECT insert_dyeing_cost_by_names('502', 'TERRA', 11.51);
SELECT insert_dyeing_cost_by_names('502', 'CASTANHO', 10.65);
SELECT insert_dyeing_cost_by_names('502', 'VINHO', 11.06);
SELECT insert_dyeing_cost_by_names('502', 'BIC', 11.42);
SELECT insert_dyeing_cost_by_names('502', 'PRATA', 10.73);

SELECT insert_dyeing_cost_by_names('503', 'BRANCO', 9.29);
SELECT insert_dyeing_cost_by_names('503', 'PRETO', 12.69);
SELECT insert_dyeing_cost_by_names('503', 'ROMANCE', 9.99);
SELECT insert_dyeing_cost_by_names('503', 'FROZEN', 10.29);
SELECT insert_dyeing_cost_by_names('503', 'CHOCOLATE', 10.29);
SELECT insert_dyeing_cost_by_names('503', 'SATIN', 10.69);
SELECT insert_dyeing_cost_by_names('503', 'ROYAL', 11.44);
SELECT insert_dyeing_cost_by_names('503', 'JAIPUR', 12.10);
SELECT insert_dyeing_cost_by_names('503', 'RACY', 11.29);
SELECT insert_dyeing_cost_by_names('503', 'ROSA BB', 10.29);
SELECT insert_dyeing_cost_by_names('503', 'AÇO', 10.49);
SELECT insert_dyeing_cost_by_names('503', 'VERMELHO', 12.26);
SELECT insert_dyeing_cost_by_names('503', 'MOCASSIM', 10.29);
SELECT insert_dyeing_cost_by_names('503', 'RUBRO', 11.06);
SELECT insert_dyeing_cost_by_names('503', 'PIMENTA', 11.91);
SELECT insert_dyeing_cost_by_names('503', 'TEOS', 9.99);
SELECT insert_dyeing_cost_by_names('503', 'CORAL', 10.33);
SELECT insert_dyeing_cost_by_names('503', 'TAME', 10.81);
SELECT insert_dyeing_cost_by_names('503', 'TW', 11.23);
SELECT insert_dyeing_cost_by_names('503', 'MARINHO', 11.29);
SELECT insert_dyeing_cost_by_names('503', 'TERRA', 11.51);
SELECT insert_dyeing_cost_by_names('503', 'CASTANHO', 10.65);
SELECT insert_dyeing_cost_by_names('503', 'VINHO', 11.06);
SELECT insert_dyeing_cost_by_names('503', 'BIC', 11.42);
SELECT insert_dyeing_cost_by_names('503', 'PRATA', 10.73);

SELECT insert_dyeing_cost_by_names('504', 'BRANCO', 9.29);
SELECT insert_dyeing_cost_by_names('504', 'PRETO', 12.69);
SELECT insert_dyeing_cost_by_names('504', 'ROMANCE', 9.99);
SELECT insert_dyeing_cost_by_names('504', 'FROZEN', 10.29);
SELECT insert_dyeing_cost_by_names('504', 'CHOCOLATE', 10.29);
SELECT insert_dyeing_cost_by_names('504', 'SATIN', 10.69);
SELECT insert_dyeing_cost_by_names('504', 'ROYAL', 11.44);
SELECT insert_dyeing_cost_by_names('504', 'JAIPUR', 12.10);
SELECT insert_dyeing_cost_by_names('504', 'RACY', 11.29);
SELECT insert_dyeing_cost_by_names('504', 'ROSA BB', 10.29);
SELECT insert_dyeing_cost_by_names('504', 'AÇO', 10.49);
SELECT insert_dyeing_cost_by_names('504', 'VERMELHO', 12.26);
SELECT insert_dyeing_cost_by_names('504', 'MOCASSIM', 10.29);
SELECT insert_dyeing_cost_by_names('504', 'RUBRO', 11.06);
SELECT insert_dyeing_cost_by_names('504', 'PIMENTA', 11.91);
SELECT insert_dyeing_cost_by_names('504', 'TEOS', 9.99);
SELECT insert_dyeing_cost_by_names('504', 'CORAL', 10.33);
SELECT insert_dyeing_cost_by_names('504', 'TAME', 10.81);
SELECT insert_dyeing_cost_by_names('504', 'TW', 11.23);
SELECT insert_dyeing_cost_by_names('504', 'MARINHO', 11.29);
SELECT insert_dyeing_cost_by_names('504', 'TERRA', 11.51);
SELECT insert_dyeing_cost_by_names('504', 'CASTANHO', 10.65);
SELECT insert_dyeing_cost_by_names('504', 'VINHO', 11.06);
SELECT insert_dyeing_cost_by_names('504', 'BIC', 11.42);
SELECT insert_dyeing_cost_by_names('504', 'PRATA', 10.73);

-- 601 - POA
SELECT insert_dyeing_cost_by_names('601', 'BRANCO', 7.62);
SELECT insert_dyeing_cost_by_names('601', 'PRETO', 9.90);
SELECT insert_dyeing_cost_by_names('601', 'ROMANCE', 7.70);
SELECT insert_dyeing_cost_by_names('601', 'FROZEN', 8.10);
SELECT insert_dyeing_cost_by_names('601', 'CHOCOLATE', 7.70);
SELECT insert_dyeing_cost_by_names('601', 'SATIN', 8.36);
SELECT insert_dyeing_cost_by_names('601', 'ROYAL', 9.13);
SELECT insert_dyeing_cost_by_names('601', 'JAIPUR', 9.84);
SELECT insert_dyeing_cost_by_names('601', 'RACY', 9.00);
SELECT insert_dyeing_cost_by_names('601', 'ROSA BB', 7.99);
SELECT insert_dyeing_cost_by_names('601', 'AÇO', 8.20);
SELECT insert_dyeing_cost_by_names('601', 'VERMELHO', 9.98);
SELECT insert_dyeing_cost_by_names('601', 'MOCASSIM', 7.99);
SELECT insert_dyeing_cost_by_names('601', 'RUBRO', 8.78);
SELECT insert_dyeing_cost_by_names('601', 'PIMENTA', 9.64);
SELECT insert_dyeing_cost_by_names('601', 'TEOS', 7.70);
SELECT insert_dyeing_cost_by_names('601', 'CORAL', 8.04);
SELECT insert_dyeing_cost_by_names('601', 'TAME', 8.52);
SELECT insert_dyeing_cost_by_names('601', 'TW', 8.95);
SELECT insert_dyeing_cost_by_names('601', 'MARINHO', 9.00);
SELECT insert_dyeing_cost_by_names('601', 'TERRA', 9.23);
SELECT insert_dyeing_cost_by_names('601', 'CASTANHO', 8.36);
SELECT insert_dyeing_cost_by_names('601', 'VINHO', 8.78);
SELECT insert_dyeing_cost_by_names('601', 'BIC', 9.13);
SELECT insert_dyeing_cost_by_names('601', 'PRATA', 8.44);

-- 701 - SUEDE LISO
SELECT insert_dyeing_cost_by_names('701', 'BRANCO', 7.62);
SELECT insert_dyeing_cost_by_names('701', 'PRETO', 9.90);
SELECT insert_dyeing_cost_by_names('701', 'ROMANCE', 7.70);
SELECT insert_dyeing_cost_by_names('701', 'FROZEN', 8.10);
SELECT insert_dyeing_cost_by_names('701', 'CHOCOLATE', 7.70);
SELECT insert_dyeing_cost_by_names('701', 'SATIN', 8.36);
SELECT insert_dyeing_cost_by_names('701', 'ROYAL', 9.13);
SELECT insert_dyeing_cost_by_names('701', 'JAIPUR', 9.84);
SELECT insert_dyeing_cost_by_names('701', 'RACY', 9.00);
SELECT insert_dyeing_cost_by_names('701', 'ROSA BB', 7.99);
SELECT insert_dyeing_cost_by_names('701', 'AÇO', 8.20);
SELECT insert_dyeing_cost_by_names('701', 'VERMELHO', 9.98);
SELECT insert_dyeing_cost_by_names('701', 'MOCASSIM', 7.99);
SELECT insert_dyeing_cost_by_names('701', 'RUBRO', 8.78);
SELECT insert_dyeing_cost_by_names('701', 'PIMENTA', 9.64);
SELECT insert_dyeing_cost_by_names('701', 'TEOS', 7.70);
SELECT insert_dyeing_cost_by_names('701', 'CORAL', 8.04);
SELECT insert_dyeing_cost_by_names('701', 'TAME', 8.52);
SELECT insert_dyeing_cost_by_names('701', 'TW', 8.95);
SELECT insert_dyeing_cost_by_names('701', 'MARINHO', 9.00);
SELECT insert_dyeing_cost_by_names('701', 'TERRA', 9.23);
SELECT insert_dyeing_cost_by_names('701', 'CASTANHO', 8.36);
SELECT insert_dyeing_cost_by_names('701', 'VINHO', 8.78);
SELECT insert_dyeing_cost_by_names('701', 'BIC', 9.13);
SELECT insert_dyeing_cost_by_names('701', 'PRATA', 8.44);

-- 801 - MEIA MALHA PV
SELECT insert_dyeing_cost_by_names('801', 'BRANCO', 5.69);
SELECT insert_dyeing_cost_by_names('801', 'PRETO', 7.49);
SELECT insert_dyeing_cost_by_names('801', 'ROMANCE', 5.69);
SELECT insert_dyeing_cost_by_names('801', 'FROZEN', 5.69);
SELECT insert_dyeing_cost_by_names('801', 'CHOCOLATE', 7.49);
SELECT insert_dyeing_cost_by_names('801', 'SATIN', 7.49);
SELECT insert_dyeing_cost_by_names('801', 'JAIPUR', 7.49);
SELECT insert_dyeing_cost_by_names('801', 'AÇO', 7.49);
SELECT insert_dyeing_cost_by_names('801', 'VERMELHO', 7.49);
SELECT insert_dyeing_cost_by_names('801', 'MOCASSIM', 5.49);
SELECT insert_dyeing_cost_by_names('801', 'RUBRO', 7.49);
SELECT insert_dyeing_cost_by_names('801', 'PIMENTA', 8.19);
SELECT insert_dyeing_cost_by_names('801', 'TEOS', 5.99);
SELECT insert_dyeing_cost_by_names('801', 'BIC', 7.19);
SELECT insert_dyeing_cost_by_names('801', 'TAME', 7.29);
SELECT insert_dyeing_cost_by_names('801', 'TW', 8.09);
SELECT insert_dyeing_cost_by_names('801', 'FANTÁSTICO', 5.49);
SELECT insert_dyeing_cost_by_names('801', 'MARINHO', 7.49);
SELECT insert_dyeing_cost_by_names('801', 'TERRA', 7.29);
SELECT insert_dyeing_cost_by_names('801', 'CASTANHO', 5.39);

-- 075 - MICRO PREMIUM PEDRINI
SELECT insert_dyeing_cost_by_names('075', 'BRANCO', 7.62);
SELECT insert_dyeing_cost_by_names('075', 'PRETO', 9.90);
SELECT insert_dyeing_cost_by_names('075', 'ROMANCE', 7.70);
SELECT insert_dyeing_cost_by_names('075', 'FROZEN', 8.10);
SELECT insert_dyeing_cost_by_names('075', 'CHOCOLATE', 7.70);
SELECT insert_dyeing_cost_by_names('075', 'SATIN', 8.36);
SELECT insert_dyeing_cost_by_names('075', 'ROYAL', 9.13);
SELECT insert_dyeing_cost_by_names('075', 'JAIPUR', 9.84);
SELECT insert_dyeing_cost_by_names('075', 'RACY', 9.00);
SELECT insert_dyeing_cost_by_names('075', 'ROSA BB', 7.99);
SELECT insert_dyeing_cost_by_names('075', 'AÇO', 8.20);
SELECT insert_dyeing_cost_by_names('075', 'VERMELHO', 9.98);
SELECT insert_dyeing_cost_by_names('075', 'MOCASSIM', 7.99);
SELECT insert_dyeing_cost_by_names('075', 'RUBRO', 8.78);
SELECT insert_dyeing_cost_by_names('075', 'PIMENTA', 9.64);
SELECT insert_dyeing_cost_by_names('075', 'TEOS', 7.70);
SELECT insert_dyeing_cost_by_names('075', 'CORAL', 8.04);
SELECT insert_dyeing_cost_by_names('075', 'TAME', 8.52);
SELECT insert_dyeing_cost_by_names('075', 'TW', 8.95);
SELECT insert_dyeing_cost_by_names('075', 'MARINHO', 9.00);
SELECT insert_dyeing_cost_by_names('075', 'TERRA', 9.23);
SELECT insert_dyeing_cost_by_names('075', 'CASTANHO', 8.36);
SELECT insert_dyeing_cost_by_names('075', 'VINHO', 8.78);
SELECT insert_dyeing_cost_by_names('075', 'BIC', 9.13);
SELECT insert_dyeing_cost_by_names('075', 'PRATA', 8.44);

-- 076 - BOX PEDRINI
SELECT insert_dyeing_cost_by_names('076', 'BRANCO', 7.62);
SELECT insert_dyeing_cost_by_names('076', 'PRETO', 9.90);
SELECT insert_dyeing_cost_by_names('076', 'ROMANCE', 7.70);
SELECT insert_dyeing_cost_by_names('076', 'FROZEN', 8.10);
SELECT insert_dyeing_cost_by_names('076', 'CHOCOLATE', 7.70);
SELECT insert_dyeing_cost_by_names('076', 'SATIN', 8.36);
SELECT insert_dyeing_cost_by_names('076', 'ROYAL', 9.13);
SELECT insert_dyeing_cost_by_names('076', 'JAIPUR', 9.84);
SELECT insert_dyeing_cost_by_names('076', 'RACY', 9.00);
SELECT insert_dyeing_cost_by_names('076', 'ROSA BB', 7.99);
SELECT insert_dyeing_cost_by_names('076', 'AÇO', 8.20);
SELECT insert_dyeing_cost_by_names('076', 'VERMELHO', 9.98);
SELECT insert_dyeing_cost_by_names('076', 'MOCASSIM', 7.99);
SELECT insert_dyeing_cost_by_names('076', 'RUBRO', 8.78);
SELECT insert_dyeing_cost_by_names('076', 'PIMENTA', 9.64);
SELECT insert_dyeing_cost_by_names('076', 'TEOS', 7.70);
SELECT insert_dyeing_cost_by_names('076', 'CORAL', 8.04);
SELECT insert_dyeing_cost_by_names('076', 'TAME', 8.52);
SELECT insert_dyeing_cost_by_names('076', 'TW', 8.95);
SELECT insert_dyeing_cost_by_names('076', 'MARINHO', 9.00);
SELECT insert_dyeing_cost_by_names('076', 'TERRA', 9.23);
SELECT insert_dyeing_cost_by_names('076', 'CASTANHO', 8.36);
SELECT insert_dyeing_cost_by_names('076', 'VINHO', 8.78);
SELECT insert_dyeing_cost_by_names('076', 'BIC', 9.13);
SELECT insert_dyeing_cost_by_names('076', 'PRATA', 8.44);

-- Cleanup: Drop the temporary function
DROP FUNCTION IF EXISTS insert_dyeing_cost_by_names(TEXT, TEXT, NUMERIC);