-- First, delete existing dyeing_costs for 401-PEDRINI, 401-LIGHT, and 401-MAX
DELETE FROM dyeing_costs 
WHERE product_id IN (
  SELECT id FROM products WHERE code IN ('401-PEDRINI', '401-LIGHT', '401-MAX')
);

-- Ensure all needed colors exist (using INSERT...ON CONFLICT to avoid duplicates)
INSERT INTO colors (name, scale, category) VALUES
  ('TIBETON', 'NORMAL', 'Cor'),
  ('BRANCO', 'NORMAL', 'Cor'),
  ('PRETO', 'NORMAL', 'Cor'),
  ('ROMANCE', 'NORMAL', 'Cor'),
  ('FROZEN', 'NORMAL', 'Cor'),
  ('CHOCOLATE', 'NORMAL', 'Cor'),
  ('SATIN', 'NORMAL', 'Cor'),
  ('SANDIA', 'NORMAL', 'Cor'),
  ('JAIPUR', 'NORMAL', 'Cor'),
  ('RACY/PINK', 'NORMAL', 'Cor'),
  ('FRUTILY', 'NORMAL', 'Cor'),
  ('AÇO', 'NORMAL', 'Cor'),
  ('VERMELHO', 'NORMAL', 'Cor'),
  ('MOCASSIM', 'NORMAL', 'Cor'),
  ('RUBRO', 'NORMAL', 'Cor'),
  ('PIMENTA', 'NORMAL', 'Cor'),
  ('TEOS', 'NORMAL', 'Cor'),
  ('BIC', 'NORMAL', 'Cor'),
  ('TAME', 'NORMAL', 'Cor'),
  ('TW', 'NORMAL', 'Cor'),
  ('FANTASTICO', 'NORMAL', 'Cor'),
  ('MARINHO', 'NORMAL', 'Cor'),
  ('TERRA', 'NORMAL', 'Cor'),
  ('ATALAIA', 'NORMAL', 'Cor'),
  ('CASTANHO', 'NORMAL', 'Cor'),
  ('MARROCOS/CALLAS', 'NORMAL', 'Cor'),
  ('BISCOITO/SUN KISS', 'NORMAL', 'Cor'),
  ('ODALISCA', 'NORMAL', 'Cor'),
  ('AZULEJO', 'NORMAL', 'Cor'),
  ('SANREMO', 'NORMAL', 'Cor'),
  ('LOTERIA', 'NORMAL', 'Cor'),
  ('TURQUESA', 'NORMAL', 'Cor'),
  ('CHRONOS', 'NORMAL', 'Cor'),
  ('PANTERA', 'NORMAL', 'Cor'),
  ('CORAL', 'NORMAL', 'Cor'),
  ('HERANÇA', 'NORMAL', 'Cor'),
  ('ROSA BB', 'NORMAL', 'Cor'),
  ('RUBRO (RONALDO)', 'NORMAL', 'Cor'),
  ('TW (DELLAS)', 'NORMAL', 'Cor'),
  ('PRETO (AMORECO)', 'NORMAL', 'Cor'),
  ('RACY (AMORECO)', 'NORMAL', 'Cor'),
  ('ROYAL', 'NORMAL', 'Cor'),
  ('EROS', 'NORMAL', 'Cor'),
  ('FLORESTA', 'NORMAL', 'Cor'),
  ('PETRÓLEO', 'NORMAL', 'Cor'),
  ('LIPSTICK/DIVINO', 'NORMAL', 'Cor'),
  ('MAJOR', 'NORMAL', 'Cor'),
  ('AMÊNDOA', 'NORMAL', 'Cor'),
  ('MOCHA MOUSSE', 'NORMAL', 'Cor'),
  ('AMÊNDOA BRONZE (FLORATA)', 'NORMAL', 'Cor'),
  ('VERDE OLIVA (FLORATA)', 'NORMAL', 'Cor'),
  ('COOFFE FLORATA', 'NORMAL', 'Cor'),
  ('COOFFE', 'NORMAL', 'Cor'),
  ('PRATA FLORATA', 'NORMAL', 'Cor'),
  ('VINHO FLORATA', 'NORMAL', 'Cor')
ON CONFLICT (name) DO NOTHING;

-- Insert dyeing costs for 401-PEDRINI (55 colors)
INSERT INTO dyeing_costs (product_id, color_id, cost)
SELECT p.id, c.id, v.cost
FROM products p
CROSS JOIN (VALUES
  ('TIBETON', 9.49),
  ('BRANCO', 7.69),
  ('PRETO', 10.09),
  ('ROMANCE', 9.09),
  ('FROZEN', 9.19),
  ('CHOCOLATE', 8.89),
  ('SATIN', 9.19),
  ('SANDIA', 9.29),
  ('JAIPUR', 10.99),
  ('RACY/PINK', 10.49),
  ('FRUTILY', 9.79),
  ('AÇO', 9.54),
  ('VERMELHO', 11.19),
  ('MOCASSIM', 9.09),
  ('RUBRO', 10.54),
  ('PIMENTA', 11.79),
  ('TEOS', 9.19),
  ('BIC', 11.39),
  ('TAME', 9.09),
  ('TW', 12.29),
  ('FANTASTICO', 9.19),
  ('MARINHO', 11.49),
  ('TERRA', 10.89),
  ('ATALAIA', 10.48),
  ('CASTANHO', 9.79),
  ('MARROCOS/CALLAS', 9.09),
  ('BISCOITO/SUN KISS', 8.89),
  ('ODALISCA', 11.19),
  ('AZULEJO', 10.19),
  ('SANREMO', 9.29),
  ('LOTERIA', 12.19),
  ('TURQUESA', 11.54),
  ('CHRONOS', 9.39),
  ('PANTERA', 9.22),
  ('CORAL', 9.19),
  ('HERANÇA', 11.09),
  ('ROSA BB', 8.79),
  ('RUBRO (RONALDO)', 10.89),
  ('TW (DELLAS)', 16.09),
  ('PRETO (AMORECO)', 13.09),
  ('RACY (AMORECO)', 11.54),
  ('ROYAL', 11.19),
  ('EROS', 9.29),
  ('FLORESTA', 11.29),
  ('PETRÓLEO', 12.29),
  ('LIPSTICK/DIVINO', 12.05),
  ('MAJOR', 11.28),
  ('AMÊNDOA', 9.64),
  ('MOCHA MOUSSE', 9.84),
  ('AMÊNDOA BRONZE (FLORATA)', 11.53),
  ('VERDE OLIVA (FLORATA)', 9.85),
  ('COOFFE FLORATA', 12.62),
  ('COOFFE', 14.46),
  ('PRATA FLORATA', 9.48),
  ('VINHO FLORATA', 12.93)
) AS v(color_name, cost)
JOIN colors c ON c.name = v.color_name
WHERE p.code = '401-PEDRINI'
ON CONFLICT DO NOTHING;

-- Insert dyeing costs for 401-LIGHT (same colors and costs as PEDRINI)
INSERT INTO dyeing_costs (product_id, color_id, cost)
SELECT p.id, c.id, v.cost
FROM products p
CROSS JOIN (VALUES
  ('TIBETON', 9.49),
  ('BRANCO', 7.69),
  ('PRETO', 10.09),
  ('ROMANCE', 9.09),
  ('FROZEN', 9.19),
  ('CHOCOLATE', 8.89),
  ('SATIN', 9.19),
  ('SANDIA', 9.29),
  ('JAIPUR', 10.99),
  ('RACY/PINK', 10.49),
  ('FRUTILY', 9.79),
  ('AÇO', 9.54),
  ('VERMELHO', 11.19),
  ('MOCASSIM', 9.09),
  ('RUBRO', 10.54),
  ('PIMENTA', 11.79),
  ('TEOS', 9.19),
  ('BIC', 11.39),
  ('TAME', 9.09),
  ('TW', 12.29),
  ('FANTASTICO', 9.19),
  ('MARINHO', 11.49),
  ('TERRA', 10.89),
  ('ATALAIA', 10.48),
  ('CASTANHO', 9.79),
  ('MARROCOS/CALLAS', 9.09),
  ('BISCOITO/SUN KISS', 8.89),
  ('ODALISCA', 11.19),
  ('AZULEJO', 10.19),
  ('SANREMO', 9.29),
  ('LOTERIA', 12.19),
  ('TURQUESA', 11.54),
  ('CHRONOS', 9.39),
  ('PANTERA', 9.22),
  ('CORAL', 9.19),
  ('HERANÇA', 11.09),
  ('ROSA BB', 8.79),
  ('RUBRO (RONALDO)', 10.89),
  ('TW (DELLAS)', 16.09),
  ('PRETO (AMORECO)', 13.09),
  ('RACY (AMORECO)', 11.54),
  ('ROYAL', 11.19),
  ('EROS', 9.29),
  ('FLORESTA', 11.29),
  ('PETRÓLEO', 12.29),
  ('LIPSTICK/DIVINO', 12.05),
  ('MAJOR', 11.28),
  ('AMÊNDOA', 9.64),
  ('MOCHA MOUSSE', 9.84),
  ('AMÊNDOA BRONZE (FLORATA)', 11.53),
  ('VERDE OLIVA (FLORATA)', 9.85),
  ('COOFFE FLORATA', 12.62),
  ('COOFFE', 14.46),
  ('PRATA FLORATA', 9.48),
  ('VINHO FLORATA', 12.93)
) AS v(color_name, cost)
JOIN colors c ON c.name = v.color_name
WHERE p.code = '401-LIGHT'
ON CONFLICT DO NOTHING;

-- Insert dyeing costs for 401-MAX (same colors and costs as PEDRINI)
INSERT INTO dyeing_costs (product_id, color_id, cost)
SELECT p.id, c.id, v.cost
FROM products p
CROSS JOIN (VALUES
  ('TIBETON', 9.49),
  ('BRANCO', 7.69),
  ('PRETO', 10.09),
  ('ROMANCE', 9.09),
  ('FROZEN', 9.19),
  ('CHOCOLATE', 8.89),
  ('SATIN', 9.19),
  ('SANDIA', 9.29),
  ('JAIPUR', 10.99),
  ('RACY/PINK', 10.49),
  ('FRUTILY', 9.79),
  ('AÇO', 9.54),
  ('VERMELHO', 11.19),
  ('MOCASSIM', 9.09),
  ('RUBRO', 10.54),
  ('PIMENTA', 11.79),
  ('TEOS', 9.19),
  ('BIC', 11.39),
  ('TAME', 9.09),
  ('TW', 12.29),
  ('FANTASTICO', 9.19),
  ('MARINHO', 11.49),
  ('TERRA', 10.89),
  ('ATALAIA', 10.48),
  ('CASTANHO', 9.79),
  ('MARROCOS/CALLAS', 9.09),
  ('BISCOITO/SUN KISS', 8.89),
  ('ODALISCA', 11.19),
  ('AZULEJO', 10.19),
  ('SANREMO', 9.29),
  ('LOTERIA', 12.19),
  ('TURQUESA', 11.54),
  ('CHRONOS', 9.39),
  ('PANTERA', 9.22),
  ('CORAL', 9.19),
  ('HERANÇA', 11.09),
  ('ROSA BB', 8.79),
  ('RUBRO (RONALDO)', 10.89),
  ('TW (DELLAS)', 16.09),
  ('PRETO (AMORECO)', 13.09),
  ('RACY (AMORECO)', 11.54),
  ('ROYAL', 11.19),
  ('EROS', 9.29),
  ('FLORESTA', 11.29),
  ('PETRÓLEO', 12.29),
  ('LIPSTICK/DIVINO', 12.05),
  ('MAJOR', 11.28),
  ('AMÊNDOA', 9.64),
  ('MOCHA MOUSSE', 9.84),
  ('AMÊNDOA BRONZE (FLORATA)', 11.53),
  ('VERDE OLIVA (FLORATA)', 9.85),
  ('COOFFE FLORATA', 12.62),
  ('COOFFE', 14.46),
  ('PRATA FLORATA', 9.48),
  ('VINHO FLORATA', 12.93)
) AS v(color_name, cost)
JOIN colors c ON c.name = v.color_name
WHERE p.code = '401-MAX'
ON CONFLICT DO NOTHING;